"""The ROM side of All Swords No Boards as bytes (docs/design/asnb.md section 3).

Generated by `python3 asm/asnb/build.py build` from asm/asnb/; do not edit.
PATCHES[name] is a tuple of (file offset, piece) writes against ZORA's code
patches (asm/series.txt, fp-prog-01 and fp-prog-02 included); each patch stands
alone. A piece is ZORA's own bytes or an Original (source, length): the original
game's bytes, read from the player's ROM when written (never stored here);
written by zora/rom/owner_patches.py from its verbatim copy, zora/rom/asnb_patch_data.py.
"""
from .base_rom import Original, Piece

PATCHES: dict[str, tuple[tuple[int, Piece], ...]] = {
    "take-l4": (
        (0x03FF0, bytes.fromhex("a50ac000d00bc903d007cd5706d002a904d9570660")),
        (0x06D04, bytes.fromhex("20e0bfeaea")),
        (0x07FF0, bytes.fromhex("a50ac000d00bc903d007cd5706d002a904d9570660")),
        (0x0BFF0, bytes.fromhex("a50ac000d00bc903d007cd5706d002a904d9570660")),
        (0x0FFF0, bytes.fromhex("a50ac000d00bc903d007cd5706d002a904d9570660")),
        (0x13FF0, bytes.fromhex("a50ac000d00bc903d007cd5706d002a904d9570660")),
        (0x17FF0, bytes.fromhex("a50ac000d00bc903d007cd5706d002a904d9570660")),
        (0x1BFF0, bytes.fromhex("a50ac000d00bc903d007cd5706d002a904d9570660")),
    ),
    "sword-cap": (
        (0x07EFC, bytes.fromhex("51e91cc902903e")),
        (0x07F13, bytes.fromhex("3a")),
        (0x07F31, bytes.fromhex("01c900a500e900b002a9008501983860ad75068501ad740618691d3860a5001860")),
        (0x10D07, bytes.fromhex("5b")),
        (0x13915, bytes.fromhex("51e91cc902903e")),
        (0x1392C, bytes.fromhex("3a")),
        (0x1394A, bytes.fromhex("01c900a500e900b002a9008501983860ad75068501ad740618691d3860a5001860a8a50148a5004898"
                                "2000b985ab6885006885014c1473")),
        (0x17865, bytes.fromhex("5b")),
        (0x1789C, bytes.fromhex("7b")),
        (0x17B15, bytes.fromhex("51e91cc902903e")),
        (0x17B2C, bytes.fromhex("3a")),
        (0x17B4A, bytes.fromhex("01c900a500e900b002a9008501983860ad75068501ad740618691d3860a5001860cd4fb8f015a8a501"
                                "48a50048982000bba868850068850198a4eb85abb9fe6a60a8a50148a50048982000bb85ab68850068"
                                "8501a9c060")),
    ),
    "level-9-gate": (
        (0x04AB2, bytes.fromhex("57")),
        (0x04AB3, Original(0x04AB3, 2)),
        (0x04AB5, bytes.fromhex("0490")),
    ),
}

# sword-cap's per-seed operand in each ResolveProgressive copy: label -> file offset.
SYMBOLS: dict[str, int] = {
    "ZORA_B1_SwordLineToL4": 0x07F33,
    "ZORA_B4_SwordLineToL4": 0x1394C,
    "ZORA_B5_SwordLineToL4": 0x17B4C,
}

# With sword-cap: ResolveProgressive's shared body per bank, (first file offset, end exclusive).
RESOLVE_COPIES: dict[int, tuple[int, int]] = {
    1: (0x07EF7, 0x07F52),
    4: (0x13910, 0x1396B),
    5: (0x17B10, 0x17B6B),
}

# take-l4's TakeGradeWithL4 in each of banks 0-6: (first file offset, end), end exclusive.
TAKE_COPIES: dict[int, tuple[int, int]] = {
    0: (0x03FF0, 0x04005),
    1: (0x07FF0, 0x08005),
    2: (0x0BFF0, 0x0C005),
    3: (0x0FFF0, 0x10005),
    4: (0x13FF0, 0x14005),
    5: (0x17FF0, 0x18005),
    6: (0x1BFF0, 0x1C005),
}
