"""ZORA's 6502 patches as bytes (docs/rom-map.md).

Generated by `python3 scripts/asm_patches.py build` from asm/; do not edit.
Each patch is a tuple of (file offset, piece) writes, against PRG0 with the
patches before it applied: a piece is ZORA's own bytes, or an Original
(source, length): bytes of the original game that the patch keeps or moves,
read from the player's ROM when it is written (never stored here).
"""
from .base_rom import Original, Piece

PATCHES: dict[str, tuple[tuple[int, Piece], ...]] = {
    "fp-lock-01": (
        (0x0909A, bytes.fromhex("eaeaea")),
        (0x09EFB, bytes.fromhex("2424242424")),
        (0x09F6A, bytes.fromhex("4c6e9f")),
        (0x0AF9C, bytes.fromhex("eaeaea")),
    ),
    "fp-fix-05": (
        (0x14AC1, bytes.fromhex("15ad5400d02b")),
        (0x14AC7, Original(0x14AC2, 33)),
    ),
    "fp-fix-06": (
        (0x17551, bytes.fromhex("a0b8")),
        (0x178B0, bytes.fromhex("ad2205c901f0034c2f7560")),
    ),
    "fp-fix-03": (
        (0x0EBF0, bytes.fromhex("a5ff29fb85ff8d00204c4480")),
        (0x1E99F, bytes.fromhex("e0ab")),
    ),
    "fp-fix-02": (
        (0x061A3, bytes.fromhex("4cc0be")),
        (0x07ED0, bytes.fromhex("ad0203c9ffd002841460")),
    ),
    "fp-entr-02": (
        (0x17553, bytes.fromhex("4cc0b8ea")),
        (0x178D0, bytes.fromhex("a5ec300da510f00cada16b297fc5ecd0034c47b54c59b5")),
    ),
    "fp-book-01": (
        (0x06C35, bytes.fromhex("4cc0ff")),
        (0x17611, bytes.fromhex("4ce0b8eaeaea")),
        (0x178F0, bytes.fromhex("8a4a9005ad6106d006bd570639bee660")),
        (0x1FFD0, bytes.fromhex("995706e011d0038ee50460")),
    ),
    "fp-hash-01": (
        (0x0A4CD, bytes.fromhex("4ca8afeaeaeaea")),
        (0x0AFB0, bytes.fromhex("0000000068788898a9148514e613a2038a48bda4af8500a92785018a0a8d4103bca0afb9c872c930d0"
                                "02a9ff290f8504b9a472aaa8203ae768aaca10d360")),
        (0x1A129, bytes.fromhex("0c180d0e24")),
        (0x1A12E, Original(0x1A12E, 1)),
        (0x1A12F, bytes.fromhex("24")),
        (0x1A130, Original(0x1A130, 1)),
        (0x1A131, bytes.fromhex("24")),
        (0x1A132, Original(0x1A132, 1)),
        (0x1A133, bytes.fromhex("24")),
        (0x1A134, Original(0x1A134, 1)),
        (0x1A135, bytes.fromhex("24")),
        (0x1A136, Original(0x1A136, 1)),
        (0x1A137, bytes.fromhex("24")),
    ),
    "fp-entr-01": (
        (0x17054, bytes.fromhex("4cc1baeaeaeaeaeaeaeaeaeaeaeaeaea")),
        (0x17AD0, bytes.fromhex("8da9788570adbb6bf00fc902d017a9088598a9dd85844c906ca9008598adc0ba85844c906ca9088598"
                                "ada66b85844c906c")),
    ),
    "fp-fix-04": (
        (0x06BF9, bytes.fromhex("2094edeaea")),
        (0x12DA1, bytes.fromhex("eaeaea")),
        (0x1EDA4, bytes.fromhex("a2028e02068e7206ee4f0360")),
    ),
    "fp-roar-01": (
        (0x065CE, bytes.fromhex("53b9")),
        (0x15359, bytes.fromhex("4c40b9ea4c49b9eaea")),
        (0x17950, bytes.fromhex("8d0106a9018d7e6c60a9008d7e6ca9804c806d20506da000a510f007ad7e6cf002a00da200b972b99d"
                                "2a03c8e8e00dd0f460207609242f15120f0e2f2424ff207609242f1b180a1b2f2424")),
    ),
    "fp-hot-01": (
        (0x0B010, bytes.fromhex("298405121d0e161cff298405190a1e1c0effa000ad7a06f002a009a200b900b09d7f6cc8e8e009d0f4"
                                "a5f82920f018ad7a06d011ac5606c00fd002a007a90120dcffa90060a92060")),
        (0x140E5, bytes.fromhex("d2b9")),
        (0x179D0, bytes.fromhex("298405121d0e161cff298405190a1e1c0eff20a7b6a5f82920f023ad7a0649018d7a06a000ad7a06f0"
                                "02a009a200b9c0b99d7f6cc8e8e009d0f4a930851460")),
        (0x1A040, bytes.fromhex("7f6c")),
        (0x1EC46, bytes.fromhex("2012b0ea")),
        (0x1FFEC, bytes.fromhex("48a90520acff6820c8b7a9024cac")),
    ),
    "fp-prog-01": (
        (0x04658, bytes.fromhex("205fbe")),
        (0x04920, bytes.fromhex("a5be")),
        (0x07E50, bytes.fromhex("0100000000ffff01020304ad500338e974a8a9ffc007b003b944be8502a8608d13048a48204bbea202"
                                "a4023008b9bee63d7706d014bd2204293f20e0be901d8503a402300da501f009a9009d3004a93f8503"
                                "bd220429c005039d2204ca10ca68aaad130460200c73204bbe300eb9bee63d41bef0061d77069d7706"
                                "60")),
        (0x07EF0, bytes.fromhex("ac40bed00218608500c91fb047e91cc9029034a400b9a4728501b9c87238e920c910b03049ff386500"
                                "a40138795706a8a9008500b9a472c501f00588e600d0f4a5008501983860ad75068501ad740618691d"
                                "3860a5001860")),
    ),
    "fp-prog-02": (
        (0x10D06, bytes.fromhex("2051b9eaea")),
        (0x13910, bytes.fromhex("8500c91fb047e91cc9029034a400b9a4728501b9c87238e920c910b03049ff386500a40138795706a8"
                                "a9008500b9a472c501f00588e600d0f4a5008501983860ad75068501ad740618691d3860a5001860a8"
                                "a50148a50048982000b985ab6885006885014c1473")),
        (0x17864, bytes.fromhex("2051bbeaea")),
        (0x1789B, bytes.fromhex("2071bbea")),
        (0x17B10, bytes.fromhex("8500c91fb047e91cc9029034a400b9a4728501b9c87238e920c910b03049ff386500a40138795706a8"
                                "a9008500b9a472c501f00588e600d0f4a5008501983860ad75068501ad740618691d3860a5001860cd"
                                "4fb8f015a8a50148a50048982000bba868850068850198a4eb85abb9fe6a60a8a50148a50048982000"
                                "bb85ab688500688501a9c060")),
    ),
}

# Data the passes fill per seed: exported label -> file offset.
SYMBOLS: dict[str, int] = {
    "ZORA_B1_OneTimeWares": 0x07E51,
    "ZORA_B1_ProgressiveItems": 0x07E50,
    "ZORA_B2_CodeIcons": 0x0AFB0,
    "ZORA_B5_BossSoundWord": 0x17994,
    "ZORA_B5_OverworldStartY": 0x17AD0,
}
