"""The ZORA 2.0 flag patches as bytes (docs/design/zora-flags-2.0.md).

Generated by `python3 asm/flags2/build.py build` from asm/flags2/; do not edit.
PATCHES[name] is a tuple of (file offset, piece) writes against ZORA's code
patches (asm/series.txt); each patch stands alone. A piece is ZORA's own bytes
or an Original (source, length): the original game's bytes, read from the
player's ROM when written (never stored here). Not wired into the serializer.
"""
from .base_rom import Original, Piece

# Community members who wrote a feature (docs/credits.md).
CREDITS: dict[str, str] = {
    "fast-heart-fill": "snarfblam",
    "recorder-pols-voice": "Stratoform",
}

PATCHES: dict[str, tuple[tuple[int, Piece], ...]] = {
    "l4-sword-beam": (
        (0x07540, bytes.fromhex("b0")),
    ),
    "l4-sword-take": (
        (0x06BEC, bytes.fromhex("43ff")),
        (0x07FD0, bytes.fromhex("ad5706c903d007c504d003ee570660")),
        (0x1FF53, bytes.fromhex("a410f00320c0bf4c0c73")),
    ),
    "raft-blocks": (
        (0x154F8, bytes.fromhex("0c")),
        (0x155F7, bytes.fromhex("0c0c")),
        (0x15613, bytes.fromhex("eb")),
        (0x15614, Original(0x15614, 1)),
        (0x15615, bytes.fromhex("af")),
        (0x15715, bytes.fromhex("b6")),
        (0x15765, bytes.fromhex("9178")),
        (0x1582F, bytes.fromhex("02080b0b0b0b0b0b0b0b01")),
        (0x1592F, bytes.fromhex("1717")),
    ),
    "bracelet-blocks": (
        (0x1554E, bytes.fromhex("38")),
        (0x1554F, Original(0x1554F, 5)),
        (0x15554, bytes.fromhex("06e7000000")),
        (0x15649, bytes.fromhex("00a9")),
        (0x1564B, Original(0x1564B, 3)),
        (0x1564E, bytes.fromhex("b6")),
        (0x1574E, bytes.fromhex("02")),
    ),
    "fast-dungeon-scroll": (
        (0x141F3, bytes.fromhex("eaea")),
        (0x1426B, bytes.fromhex("eaea")),
        (0x1446B, bytes.fromhex("eaea")),
        (0x14478, bytes.fromhex("eaea")),
        (0x144AD, bytes.fromhex("eaea")),
    ),
    "fast-heart-fill": (
        (0x17203, bytes.fromhex("e8")),
        (0x17204, Original(0x17204, 4)),
        (0x17208, bytes.fromhex("18")),
    ),
    "recorder-pols-voice": (
        (0x11BB2, bytes.fromhex("2000baea")),
        (0x13A10, bytes.fromhex("ad1b05f00ebd85048507a901850920547c686860")),
    ),
    "four-potions": (
        (0x06C70, bytes.fromhex("05")),
        (0x06C71, Original(0x06C71, 3)),
        (0x06C74, bytes.fromhex("04")),
    ),
    "auto-show-letter": (
        (0x04708, bytes.fromhex("c901f013eaeaeaeaeaeaeaeaea")),
    ),
    "like-like-rupees": (
        (0x11D45, bytes.fromhex("01")),
        (0x11D46, Original(0x11D46, 1)),
        (0x11D47, bytes.fromhex("7e")),
    ),
    "magic-boomerang-damage": (
        (0x07478, bytes.fromhex("a95099ac00a5093db204f00420c57d60a910953dad75060a0a0a0a8507ea")),
    ),
    "lost-hills": (
        (0x154D7, bytes.fromhex("01010101010101")),
        (0x154F1, bytes.fromhex("09")),
        (0x154F2, Original(0x154F2, 3)),
        (0x154F5, bytes.fromhex("06")),
        (0x155DD, bytes.fromhex("02")),
        (0x155F5, bytes.fromhex("51")),
    ),
    "dead-woods": (
        (0x15B08, bytes.fromhex("29")),
    ),
}
