"""Player-setting patches as bytes (docs/player-settings-patches.md).

Generated by `python3 asm/settings/build.py build` from asm/settings/;
do not edit. SETTINGS[setting][choice] is a tuple of (file offset, piece):
every choice of a setting writes the same offsets, so writing a choice
selects it whatever the ROM held. Apply after ZORA's code patches. A piece
is ZORA's own bytes or an Original (source, length): the original game's
bytes, read from the player's ROM when written (never stored here).
"""
from zora.rom.base_rom import Original, Piece

DEFAULTS: dict[str, str] = {
    "select_swap": "toggle",  # FP-HOT-01
    "death_warp": "controller1_up_a",  # FP-RESET-01
    "music": "on",  # FP-SET-04
    "reduce_flashing": "off",  # FP-FIX-02
}

SETTINGS: dict[str, dict[str, tuple[tuple[int, Piece], ...]]] = {
    "select_swap": {
        "toggle": (
            (0x0B010, bytes.fromhex("298405121d0e161cff298405190a1e1c0effa000ad7a06f002a009a200b900b09d7f6cc8e8e009"
                                    "d0f4a5f82920f018ad7a06d011ac5606c00fd002a007a90120dcffa90060a92060")),
            (0x140E5, bytes.fromhex("d2b9")),
            (0x1A040, bytes.fromhex("7f6c")),
            (0x1EC47, bytes.fromhex("12")),
        ),
        "swap_only": (
            (0x0B010, bytes.fromhex("a5f82920f010ac5606c00fd002a007a90120dcffa90060ffffffffffffffffffffffffffffffff"
                                    "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff")),
            (0x140E5, bytes.fromhex("a7b6")),
            (0x1A040, bytes.fromhex("16a3")),
            (0x1EC47, bytes.fromhex("00")),
        ),
    },
    "death_warp": {
        "controller2_up_a": (
            (0x140EB, Original(0x140EB, 5)),
            (0x179EA, bytes.fromhex("23ad7a0649018d7a06a000ad7a06f002a009a200b9c0b99d7f6cc8e8e009d0f4a930851460ffff"
                                    "ffffffff")),
        ),
        "controller1_up_a": (
            (0x140EB, bytes.fromhex("fa")),
            (0x140EC, Original(0x140EC, 4)),
            (0x179EA, bytes.fromhex("23ad7a0649018d7a06a000ad7a06f002a009a200b9c0b99d7f6cc8e8e009d0f4a930851460ffff"
                                    "ffffffff")),
        ),
        "controller1_up_select": (
            (0x140EB, bytes.fromhex("fa")),
            (0x140EC, Original(0x140EC, 1)),
            (0x140ED, bytes.fromhex("28")),
            (0x140EE, Original(0x140EE, 1)),
            (0x140EF, bytes.fromhex("28")),
            (0x179EA, bytes.fromhex("29a5fa2908d023ad7a0649018d7a06a000ad7a06f002a009a200b9c0b99d7f6cc8e8e009d0f4a9"
                                    "30851460")),
        ),
    },
    "music": {
        "on": (
            (0x01C7B, Original(0x01C7B, 3)),
            (0x02010, bytes.fromhex("ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff")),
        ),
        "off": (
            (0x01C7B, bytes.fromhex("20")),
            (0x01C7C, Original(0x01C7C, 1)),
            (0x01C7D, bytes.fromhex("a0")),
            (0x02010, bytes.fromhex("ad0006c901f00bc940f007c920f003090060ad0906f00320469da90060")),
        ),
    },
    "reduce_flashing": {
        "off": (
            (0x06A5B, Original(0x06A5B, 2)),
            (0x07ED7, bytes.fromhex("8414")),
            (0x0AA30, Original(0x0AA30, 3)),
            (0x16895, Original(0x16895, 2)),
        ),
        "on": (
            (0x06A5B, bytes.fromhex("eaea")),
            (0x07ED7, bytes.fromhex("eaea")),
            (0x0AA30, bytes.fromhex("0f0f0f")),
            (0x16895, bytes.fromhex("eaea")),
        ),
    },
}
