"""The tables of docs/spec/flags-behavior.md that the flag tests check against.

The tests read them from tests/flags_spec_fixture.py, so the suite runs without
docs/spec/. This module extracts them from the spec, writes the fixture, and is
how tests/test_spec_fixtures.py checks that the fixture still matches the spec:

    python3 tests/flags_spec_tables.py      rewrite tests/flags_spec_fixture.py
"""
from __future__ import annotations

import json
import re
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
SPEC_PATH = REPO / "docs" / "spec" / "flags-behavior.md"
FIXTURE_PATH = REPO / "tests" / "flags_spec_fixture.py"

PRESET_NAMES = ("MVP baseline", "Published variant A", "Published variant B", "Published variant C")
PRESET_ENTRIES = ("FL-PRE-01", "FL-PRE-02", "FL-PRE-03", "FL-PRE-04")
# FL-ALT-01 names the values the support matrix produces in this phrase.
ALTERNATIVE_VALUES_PHRASE = "C16 = 3, C20 = 1 and C03 = 2"
FIELD_ID = re.compile(r"[BC]\d\d$")
# B14 and B16's setting name in the spec adds where they have no effect; the fixture keeps
# ZORA's shorter name for them (FL-DEP-05: they change nothing in the game).
INERT_SETTING_NAME = re.compile(r"\(No effect in [^;)]*")

FIXTURE_HEADER = '''# ruff: noqa: E501
"""Tables of docs/spec/flags-behavior.md, as the flag tests need them.

Generated by `python3 tests/flags_spec_tables.py` from the spec (its commit is
in docs/spec/MANIFEST.txt); do not edit. tests/test_spec_fixtures.py checks,
when docs/spec/ is present, that this still matches the spec. Each row is a
markdown table row split into its cells, in ZORA's wording where it differs
(B14 and B16's setting name).

  FIELD_SETTING_ROWS     FL-ENC-04/05: field ID and setting name
  CHECKPOINT_ROWS        the B11 checkpoint table (CP-1 to CP-13)
  PRESET_OPTION_ROWS,
  PRESET_TOGGLE_ROWS     FL-PRE-05: the four presets' values per field
  PRESET_STRINGS         FL-PRE-01 to FL-PRE-04: each preset's flag string
  SUPPORT_OPTION_ROWS    FL-SUP-02: the option fields' support matrix
  SUPPORT_TOGGLE_ROWS    FL-SUP-03: the three-state fields' support matrix
  TURN_OFF_ROWS          FL-OFF-07: the turn-off values
  ALTERNATIVE_VALUES     FL-ALT-01: the phrase naming the alternative values
"""
'''


def section(spec: str, start: str, end: str) -> str:
    begin = spec.index(start)
    return spec[begin:spec.index(end, begin)]


def table_rows(text: str, prefix: str) -> Iterator[list[str]]:
    for line in text.splitlines():
        if line.startswith(prefix):
            yield [zora_wording(cell.strip()) for cell in line.strip().strip("|").split("|")]


def zora_wording(cell: str) -> str:
    return INERT_SETTING_NAME.sub("(No effect", cell)


def preset_string(spec: str, preset: str, entry: str) -> str:
    match = re.search(rf"\*\*{entry}\. {re.escape(preset)}.*?\n`([^`]+)`", spec)
    assert match, entry
    return match.group(1)


def extract(spec: str) -> dict[str, Any]:
    """The tables, in the fixture's names."""
    presets = section(spec, "**FL-PRE-05.", "## FL-SUP")
    assert ALTERNATIVE_VALUES_PHRASE in spec.replace("\n", " ")
    return {
        "FIELD_SETTING_ROWS": [row[:2] for row in table_rows(section(spec, "**FL-ENC-04.", "**FL-ENC-06."), "| ")
                               if FIELD_ID.match(row[0])],
        "CHECKPOINT_ROWS": list(table_rows(section(spec, "## Checkpoint (B11", "## Known open issues"), "| CP-")),
        "PRESET_OPTION_ROWS": list(table_rows(presets, "| C")),
        "PRESET_TOGGLE_ROWS": list(table_rows(presets, "| B")),
        "PRESET_STRINGS": {preset: preset_string(spec, preset, entry)
                           for preset, entry in zip(PRESET_NAMES, PRESET_ENTRIES, strict=True)},
        "SUPPORT_OPTION_ROWS": list(table_rows(section(spec, "**FL-SUP-02.", "**FL-SUP-03."), "| C")),
        "SUPPORT_TOGGLE_ROWS": list(table_rows(section(spec, "**FL-SUP-03.", "**FL-SUP-04."), "| B")),
        # FL-OFF-07: | ID | Setting | MVP baseline | Turn-off value | Entry | (the header row left out)
        "TURN_OFF_ROWS": list(table_rows(section(spec, "**FL-OFF-07.", "## FL-SEED"), "| "))[1:],
        "ALTERNATIVE_VALUES": ALTERNATIVE_VALUES_PHRASE,
    }


def render(tables: dict[str, Any]) -> str:
    """The fixture's source: one table row per line, strings in double quotes (JSON's
    notation, which is also Python's for lists, dicts and strings)."""
    parts = [FIXTURE_HEADER]
    for name, value in tables.items():
        if isinstance(value, list):
            rows = "".join(f"    {json.dumps(row, ensure_ascii=False)},\n" for row in value)
            parts.append(f"\n{name} = [\n{rows}]\n")
        elif isinstance(value, dict):
            items = "".join(f"    {json.dumps(key)}: {json.dumps(text, ensure_ascii=False)},\n"
                            for key, text in value.items())
            parts.append(f"\n{name} = {{\n{items}}}\n")
        else:
            parts.append(f"\n{name} = {json.dumps(value, ensure_ascii=False)}\n")
    return "".join(parts)


def main() -> int:
    FIXTURE_PATH.write_text(render(extract(SPEC_PATH.read_text())))
    sys.stdout.write(f"wrote {FIXTURE_PATH.relative_to(REPO)}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
