# AUTO-GENERATED by flags/validate_flags.py
# DO NOT EDIT MANUALLY
# To regenerate: python flags/validate_flags.py --generate
# Schema version: 1
# Generated from: flags/flags.yaml

from __future__ import annotations
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Any
from zora.rng import Rng


# ===========================================================================
# TRISTATE ENUM
# ===========================================================================

class Tristate(IntEnum):
    """Tri-state flag value: off, on, or random."""
    OFF = 0
    ON = 1
    RANDOM = 2


# ===========================================================================
# ITEM ENUM
# ===========================================================================

class Item(IntEnum):
    """Canonical item identifiers for item-type flag fields."""
    RANDOM = 0
    WOOD_SWORD = 1
    WHITE_SWORD = 2
    MAGICAL_SWORD = 3
    WOOD_ARROWS = 4
    SILVER_ARROWS = 5
    BOW = 6
    BLUE_CANDLE = 7
    RED_CANDLE = 8
    BLUE_RING = 9
    RED_RING = 10
    POWER_BRACELET = 11
    LADDER = 12
    RAFT = 13
    RECORDER = 14
    MAGICAL_KEY = 15
    BOOMERANG = 16
    MAGICAL_BOOMERANG = 17
    WAND = 18
    LETTER = 19
    BAIT = 20
    BLUE_POTION = 21
    HEART_CONTAINER = 22
    NOT_SHUFFLED = 31


ITEM_LABELS: dict[Item, str] = {
    Item.RANDOM: "Random",
    Item.WOOD_SWORD: "Wood Sword",
    Item.WHITE_SWORD: "White Sword",
    Item.MAGICAL_SWORD: "Magical Sword",
    Item.WOOD_ARROWS: "Wood Arrows",
    Item.SILVER_ARROWS: "Silver Arrows",
    Item.BOW: "Bow",
    Item.BLUE_CANDLE: "Blue Candle",
    Item.RED_CANDLE: "Red Candle",
    Item.BLUE_RING: "Blue Ring",
    Item.RED_RING: "Red Ring",
    Item.POWER_BRACELET: "Power Bracelet",
    Item.LADDER: "Ladder",
    Item.RAFT: "Raft",
    Item.RECORDER: "Recorder",
    Item.MAGICAL_KEY: "Magical Key",
    Item.BOOMERANG: "Boomerang",
    Item.MAGICAL_BOOMERANG: "Magical Boomerang",
    Item.WAND: "Wand",
    Item.LETTER: "Letter",
    Item.BAIT: "Bait",
    Item.BLUE_POTION: "Blue Potion",
    Item.HEART_CONTAINER: "Heart Container",
    Item.NOT_SHUFFLED: "Not Shuffled",
}


# ===========================================================================
# HINTMODE ENUM  (flag: hint_mode)
# ===========================================================================

class HintMode(IntEnum):
    """Values for the hint_mode flag."""
    VANILLA = 0
    BLANK = 1
    COMMUNITY = 2
    HELPFUL = 3
    RANDOM = 4


# ===========================================================================
# VISUALROARSOUND ENUM  (flag: visual_roar_sound)
# ===========================================================================

class VisualRoarSound(IntEnum):
    """Values for the visual_roar_sound flag."""
    DISABLED = 0
    ROAR = 1
    RAWR = 2
    MEOW = 3
    WOOF = 4
    HISS = 5
    HONK = 6
    RANDOM = 7


# ===========================================================================
# CAVESHUFFLEMODE ENUM  (flag: cave_shuffle_mode)
# ===========================================================================

class CaveShuffleMode(IntEnum):
    """Values for the cave_shuffle_mode flag."""
    VANILLA = 0
    DUNGEONS_ONLY = 1
    NON_DUNGEONS_ONLY = 2
    ALL_CAVES = 3


# ===========================================================================
# STARTSCREEN ENUM  (flag: start_screen)
# ===========================================================================

class StartScreen(IntEnum):
    """Values for the start_screen flag."""
    VANILLA = 0
    EASY_SHUFFLE = 1
    FULL_SHUFFLE = 2
    WOOD_SWORD_SCREEN = 3


# ===========================================================================
# ENEMYHP ENUM  (flag: enemy_hp)
# ===========================================================================

class EnemyHp(IntEnum):
    """Values for the enemy_hp flag."""
    NORMAL = 0
    PLUS_MINUS_2 = 1
    PLUS_MINUS_4 = 2
    ZERO = 3
    RANDOM = 4


# ===========================================================================
# BOSSHP ENUM  (flag: boss_hp)
# ===========================================================================

class BossHp(IntEnum):
    """Values for the boss_hp flag."""
    NORMAL = 0
    PLUS_MINUS_2 = 1
    PLUS_MINUS_4 = 2
    ZERO = 3
    RANDOM = 4


# ===========================================================================
# SELECTSWAPMODE ENUM  (flag: select_swap_mode)
# ===========================================================================

class SelectSwapMode(IntEnum):
    """Values for the select_swap_mode flag."""
    PAUSE = 0
    SWAP = 1
    TOGGLE = 2


# ===========================================================================
# DEATHWARPBUTTON ENUM  (flag: deathwarp_button)
# ===========================================================================

class DeathwarpButton(IntEnum):
    """Values for the deathwarp_button flag."""
    P2_UP_A = 0
    P1_UP_A = 1
    P1_UP_SEL = 2


# ===========================================================================
# LOWHEARTSSOUND ENUM  (flag: low_hearts_sound)
# ===========================================================================

class LowHeartsSound(IntEnum):
    """Values for the low_hearts_sound flag."""
    REGULAR = 0
    SOFTER = 1
    DISABLED = 2


# ===========================================================================
# LEVELNAME ENUM  (flag: level_name)
# ===========================================================================

class LevelName(IntEnum):
    """Values for the level_name flag."""
    LEVEL = 0
    RANDOM_CHOICE = 1
    ABODE = 2
    ACT = 3
    AREA = 4
    ASYLUM = 5
    BOARD = 6
    CAGE = 7
    CAMP = 8
    CAVE = 9
    CORRAL = 10
    LAIR = 11
    PALACE = 12
    PLACE = 13
    RANDOM_NAME = 14
    REALM = 15
    REGION = 16
    SECTOR = 17
    SPHERE = 18
    STAGE = 19
    TEMPLE = 20
    WORLD = 21
    ZONE = 22


# ===========================================================================
# FLAGS DATACLASS
# ===========================================================================

@dataclass
class Flags:
    """Randomizer configuration flags (excludes cosmetic flags).

    Auto-generated from flags/flags.yaml. Do not edit manually.
    Run `python flags/validate_flags.py --generate` to regenerate.
    """

    # Item Shuffle
    shuffle_dungeon_items: Tristate = Tristate.OFF
    shuffle_dungeon_hearts: Tristate = Tristate.OFF
    shuffle_within_dungeons: Tristate = Tristate.OFF
    allow_triforces_in_stairways: Tristate = Tristate.OFF
    add_l4_sword: bool = False
    shuffle_wood_sword: Tristate = Tristate.OFF
    shuffle_magical_sword: Tristate = Tristate.OFF
    shuffle_letter: Tristate = Tristate.OFF
    shuffle_major_shop_items: Tristate = Tristate.OFF
    shuffle_blue_potion: Tristate = Tristate.OFF
    add_extra_candles: Tristate = Tristate.OFF
    progressive_items: Tristate = Tristate.OFF
    allow_important_in_l9: Tristate = Tristate.OFF
    force_rr_to_l9: Tristate = Tristate.OFF
    force_sa_to_l9: Tristate = Tristate.OFF
    white_sword_item: Item = Item.NOT_SHUFFLED
    armos_item: Item = Item.NOT_SHUFFLED
    coast_item: Item = Item.NOT_SHUFFLED

    # Misc
    hint_mode: HintMode = HintMode.VANILLA
    randomize_dungeon_palettes: Tristate = Tristate.OFF
    permanent_sword_beam: Tristate = Tristate.OFF
    visual_roar_sound: VisualRoarSound = VisualRoarSound.DISABLED
    book_is_an_atlas: Tristate = Tristate.OFF
    book_is_a_translator: Tristate = Tristate.OFF
    replace_book_fire_with_explosion: Tristate = Tristate.OFF
    avoid_required_hard_combat: Tristate = Tristate.OFF
    magical_boomerang_does_one_hp_damage: bool = False

    # Caves and Shops
    shuffle_shop_items: Tristate = Tristate.OFF
    randomize_white_sword_hearts: bool = False
    randomize_magical_sword_hearts: bool = False
    randomize_bomb_upgrade: Tristate = Tristate.OFF
    randomize_mmg: Tristate = Tristate.OFF

    # Quality of Life
    fast_fill: Tristate = Tristate.OFF
    speed_up_text: Tristate = Tristate.OFF
    speed_up_dungeon_transitions: Tristate = Tristate.OFF
    fix_known_bugs: Tristate = Tristate.OFF
    auto_show_letter: Tristate = Tristate.OFF
    four_potion_inventory: Tristate = Tristate.OFF
    flute_kills_pols: Tristate = Tristate.OFF
    like_like_rupees: Tristate = Tristate.OFF

    # Overworld
    cave_shuffle_mode: CaveShuffleMode = CaveShuffleMode.VANILLA
    include_wood_sword_cave: Tristate = Tristate.OFF
    include_any_road_caves: Tristate = Tristate.OFF
    start_screen: StartScreen = StartScreen.VANILLA
    update_recorder_warp_screens: Tristate = Tristate.OFF
    shuffle_armos_location: Tristate = Tristate.OFF
    extra_raft_blocks: Tristate = Tristate.OFF
    extra_power_bracelet_blocks: Tristate = Tristate.OFF
    randomize_lost_hills: Tristate = Tristate.OFF
    randomize_dead_woods: Tristate = Tristate.OFF

    # Enemies
    shuffle_overworld_monsters: Tristate = Tristate.OFF
    shuffle_dungeon_monsters: Tristate = Tristate.OFF
    shuffle_ganon_zelda: Tristate = Tristate.OFF
    shuffle_level_9_monsters: Tristate = Tristate.OFF
    shuffle_monsters_between_levels: Tristate = Tristate.OFF
    add_2nd_quest_monsters: Tristate = Tristate.OFF
    shuffle_enemy_groups: Tristate = Tristate.OFF
    shuffle_bosses: Tristate = Tristate.OFF
    change_dungeon_boss_groups: Tristate = Tristate.OFF
    enemy_hp: EnemyHp = EnemyHp.NORMAL
    boss_hp: BossHp = BossHp.NORMAL
    ganon_hp_to_zero: Tristate = Tristate.OFF

    # Schema metadata — used for sync checking, not a flag
    _schema_version: int = field(default=1, init=False, repr=False, compare=False)
    _schema_hash: str = field(default="7fa68d322faa7d9d", init=False, repr=False, compare=False)


# ===========================================================================
# COSMETIC FLAGS DATACLASS
# ===========================================================================

@dataclass
class CosmeticFlags:
    """Cosmetic-only flags encoded in a separate string from Flags.

    These do not affect item placement, seed generation, or the hash code.
    Players can share the same seed + flag_string with different cosmetic
    settings and get the same logical game.

    Auto-generated from flags/flags.yaml. Do not edit manually.
    Run `python flags/validate_flags.py --generate` to regenerate.
    """

    select_swap_mode: SelectSwapMode = SelectSwapMode.PAUSE
    deathwarp_button: DeathwarpButton = DeathwarpButton.P2_UP_A
    low_hearts_sound: LowHeartsSound = LowHeartsSound.REGULAR
    disable_music: Tristate = Tristate.OFF
    level_name: LevelName = LevelName.LEVEL
    reduce_flashing: Tristate = Tristate.OFF
    green_tunic_color: int = 0
    blue_ring_color: int = 0
    red_ring_color: int = 0
    heart_color: int = 0


# ===========================================================================
# ENCODING CONSTANTS
# ===========================================================================

BASE64_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@abcdefghijklmnopqrstuvwxyz"
FLAG_STRING_LENGTH = 25
TOTAL_BITS = 150
COSMETIC_FLAG_STRING_LENGTH = 7
COSMETIC_TOTAL_BITS = 42

# (flag_id, bit_offset, bit_width) — used by encoder/decoder
_FLAG_LAYOUT: list[tuple[str, int, int]] = [
    ("shuffle_dungeon_items", 0, 2),
    ("shuffle_dungeon_hearts", 2, 2),
    ("shuffle_within_dungeons", 8, 2),
    ("allow_important_in_l9", 10, 2),
    ("allow_triforces_in_stairways", 12, 2),
    ("force_rr_to_l9", 14, 2),
    ("force_sa_to_l9", 16, 2),
    ("shuffle_letter", 18, 2),
    ("shuffle_wood_sword", 20, 2),
    ("shuffle_magical_sword", 22, 2),
    ("shuffle_major_shop_items", 24, 2),
    ("shuffle_blue_potion", 26, 2),
    ("progressive_items", 28, 2),
    ("white_sword_item", 30, 5),
    ("armos_item", 35, 5),
    ("coast_item", 40, 5),
    ("avoid_required_hard_combat", 47, 2),
    ("randomize_dungeon_palettes", 49, 2),
    ("hint_mode", 51, 3),
    ("randomize_bomb_upgrade", 55, 2),
    ("randomize_mmg", 57, 2),
    ("start_screen", 60, 2),
    ("cave_shuffle_mode", 62, 3),
    ("shuffle_armos_location", 65, 2),
    ("include_wood_sword_cave", 67, 2),
    ("include_any_road_caves", 69, 2),
    ("speed_up_dungeon_transitions", 71, 2),
    ("speed_up_text", 73, 2),
    ("extra_raft_blocks", 75, 2),
    ("extra_power_bracelet_blocks", 77, 2),
    ("randomize_lost_hills", 79, 2),
    ("randomize_dead_woods", 81, 2),
    ("add_extra_candles", 83, 2),
    ("fast_fill", 85, 2),
    ("flute_kills_pols", 87, 2),
    ("four_potion_inventory", 91, 2),
    ("auto_show_letter", 93, 2),
    ("like_like_rupees", 95, 2),
    ("randomize_white_sword_hearts", 97, 1),
    ("randomize_magical_sword_hearts", 98, 1),
    ("permanent_sword_beam", 99, 2),
    ("book_is_an_atlas", 101, 2),
    ("book_is_a_translator", 105, 2),
    ("visual_roar_sound", 107, 3),
    ("replace_book_fire_with_explosion", 110, 2),
    ("fix_known_bugs", 112, 2),
    ("shuffle_shop_items", 114, 2),
    ("update_recorder_warp_screens", 120, 2),
    ("magical_boomerang_does_one_hp_damage", 122, 1),
    ("add_l4_sword", 123, 1),
    ("shuffle_overworld_monsters", 124, 2),
    ("shuffle_dungeon_monsters", 126, 2),
    ("shuffle_ganon_zelda", 128, 2),
    ("shuffle_level_9_monsters", 130, 2),
    ("shuffle_monsters_between_levels", 132, 2),
    ("add_2nd_quest_monsters", 134, 2),
    ("enemy_hp", 136, 3),
    ("boss_hp", 139, 3),
    ("ganon_hp_to_zero", 142, 2),
    ("shuffle_enemy_groups", 144, 2),
    ("shuffle_bosses", 146, 2),
    ("change_dungeon_boss_groups", 148, 2),
]

# (flag_id, cosmetic_bit_offset, bit_width) — used by cosmetic encoder/decoder
_COSMETIC_FLAG_LAYOUT: list[tuple[str, int, int]] = [
    ("select_swap_mode", 0, 2),
    ("deathwarp_button", 2, 2),
    ("low_hearts_sound", 4, 2),
    ("disable_music", 6, 2),
    ("level_name", 8, 5),
    ("reduce_flashing", 13, 2),
    ("green_tunic_color", 15, 6),
    ("blue_ring_color", 21, 6),
    ("red_ring_color", 27, 6),
    ("heart_color", 33, 6),
]


# ===========================================================================
# ENCODER / DECODER
# ===========================================================================

def encode_flags(flags: Flags) -> str:
    """Encode a Flags instance to a base62 flag string."""
    bitfield = 0
    for fid, offset, width in _FLAG_LAYOUT:
        value = int(getattr(flags, fid, 0))
        mask = (1 << width) - 1
        bitfield |= (value & mask) << offset
    chars = []
    remaining = bitfield
    for _ in range(FLAG_STRING_LENGTH):
        chars.append(BASE64_ALPHABET[remaining & 0x3F])
        remaining >>= 6
    return "".join(chars)


def decode_flags(flag_string: str) -> Flags:
    """Decode a base62 flag string into a Flags instance.

    Short strings are right-padded with '0' for backwards compatibility.
    Unrecognised characters raise ValueError.
    """
    # Validate characters
    for ch in flag_string:
        if ch not in BASE64_ALPHABET:
            raise ValueError(f"Invalid character {ch!r} in flag string")
    # Pad for backwards compatibility
    flag_string = flag_string.ljust(FLAG_STRING_LENGTH, "A")
    if len(flag_string) > FLAG_STRING_LENGTH:
        raise ValueError(
            f"Flag string length {len(flag_string)} exceeds maximum {FLAG_STRING_LENGTH}"
        )
    bitfield = 0
    for i, ch in enumerate(flag_string):
        bitfield |= BASE64_ALPHABET.index(ch) << (i * 6)
    kwargs: dict[str, Any] = {}
    for fid, offset, width in _FLAG_LAYOUT:
        flag_def = _FLAG_DEFS[fid]
        if not flag_def.get("enabled", True):
            continue  # disabled flags are not fields on the Flags dataclass
        mask = (1 << width) - 1
        raw = (bitfield >> offset) & mask
        # Map raw int to appropriate type
        if flag_def["type"] == "tristate":
            kwargs[fid] = Tristate(min(raw, 2))  # clamp; 3 is invalid → OFF
        elif flag_def["type"] == "item":
            max_item = max(e["index"] for e in _ITEM_ENUM)
            kwargs[fid] = Item(raw) if raw <= max_item else Item.RANDOM
        elif flag_def["type"] == "enum":
            from importlib import import_module as _im
            _mod = _im(__name__)
            _cls_name = "".join(w.capitalize() for w in fid.split("_"))
            _cls = getattr(_mod, _cls_name)
            max_val = len(flag_def["values"]) - 1
            kwargs[fid] = _cls(min(raw, max_val))
        else:
            kwargs[fid] = bool(raw)
    return Flags(**kwargs)


def encode_cosmetic_flags(flags: CosmeticFlags) -> str:
    """Encode a CosmeticFlags instance to a cosmetic flag string."""
    bitfield = 0
    for fid, offset, width in _COSMETIC_FLAG_LAYOUT:
        value = int(getattr(flags, fid, 0))
        mask = (1 << width) - 1
        bitfield |= (value & mask) << offset
    chars = []
    remaining = bitfield
    for _ in range(COSMETIC_FLAG_STRING_LENGTH):
        chars.append(BASE64_ALPHABET[remaining & 0x3F])
        remaining >>= 6
    return "".join(chars)


def decode_cosmetic_flags(flag_string: str) -> CosmeticFlags:
    """Decode a cosmetic flag string into a CosmeticFlags instance.

    Short strings are right-padded with 'A' (vanilla defaults).
    Unrecognised characters raise ValueError.
    """
    for ch in flag_string:
        if ch not in BASE64_ALPHABET:
            raise ValueError(f"Invalid character {ch!r} in cosmetic flag string")
    flag_string = flag_string.ljust(COSMETIC_FLAG_STRING_LENGTH, "A")
    if len(flag_string) > COSMETIC_FLAG_STRING_LENGTH:
        raise ValueError(
            f"Cosmetic flag string length {len(flag_string)} exceeds maximum {COSMETIC_FLAG_STRING_LENGTH}"
        )
    bitfield = 0
    for i, ch in enumerate(flag_string):
        bitfield |= BASE64_ALPHABET.index(ch) << (i * 6)
    kwargs: dict[str, Any] = {}
    for fid, offset, width in _COSMETIC_FLAG_LAYOUT:
        flag_def = _FLAG_DEFS[fid]
        if not flag_def.get("enabled", True):
            continue
        mask = (1 << width) - 1
        raw = (bitfield >> offset) & mask
        if flag_def["type"] == "tristate":
            kwargs[fid] = Tristate(min(raw, 2))
        elif flag_def["type"] == "enum":
            from importlib import import_module as _im
            _mod = _im(__name__)
            _cls_name = "".join(w.capitalize() for w in fid.split("_"))
            _cls = getattr(_mod, _cls_name)
            max_val = len(flag_def["values"]) - 1
            kwargs[fid] = _cls(min(raw, max_val))
        elif flag_def["type"] == "color":
            kwargs[fid] = min(raw, (1 << width) - 1)
        else:
            kwargs[fid] = bool(raw)
    return CosmeticFlags(**kwargs)


# ===========================================================================
# RUNTIME METADATA
# ===========================================================================

# Full flag definitions for runtime introspection (e.g. UI generation)
# enum-type flags have 'index' injected into each value entry at generation time.
_FLAG_DEFS: dict[str, dict[str, Any]] = {
    "shuffle_dungeon_items": {
        "id": "shuffle_dungeon_items",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 0,
        "label": "Shuffle Dungeon Items",
        "description": (
            "Adds the 12 major dungeon items to the item pool and makes their vanilla locations valid placement"
            "destinations. The 12 items are: bow, boomerang, magical boomerang, raft, ladder, recorder, wand, red"
            "candle, book of magic, magical key, silver arrows, and red ring. When off, dungeon item locations retain"
            "their vanilla contents.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 10,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "shuffle_dungeon_hearts": {
        "id": "shuffle_dungeon_hearts",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 2,
        "label": "Shuffle Dungeon Hearts",
        "description": (
            "Adds the 8 boss heart containers (levels 1-8) to the item pool. Requires Shuffle Dungeon Items to be"
            "enabled.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 20,
        "default": "off",
        "depends_on": "shuffle_dungeon_items",
        "enabled": True,
        "phase": 1,
    },
    "shuffle_within_dungeons": {
        "id": "shuffle_within_dungeons",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 8,
        "label": "Shuffle Within Dungeons",
        "description": (
            "Shuffles major and minor items within each dungeon in addition to the normal dungeon item shuffle.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 50,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "allow_triforces_in_stairways": {
        "id": "allow_triforces_in_stairways",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 12,
        "label": "Allow Triforces in Stairways",
        "description": (
            "Extends Shuffle Within Dungeons to also allow triforce pieces to be placed in item stairway locations"
            "within dungeons. Requires Shuffle Within Dungeons to be enabled.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 60,
        "default": "off",
        "depends_on": "shuffle_within_dungeons",
        "enabled": True,
        "phase": 1,
    },
    "shuffle_wood_sword": {
        "id": "shuffle_wood_sword",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 20,
        "label": "Shuffle Wood Sword",
        "description": (
            "Adds the wood sword to the item pool and makes the wood sword cave a valid item placement destination.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 110,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "shuffle_magical_sword": {
        "id": "shuffle_magical_sword",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 22,
        "label": "Shuffle Magical Sword",
        "description": (
            "Adds the magical sword to the item pool and makes the magical sword cave a valid item placement"
            "destination.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 120,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "shuffle_letter": {
        "id": "shuffle_letter",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 18,
        "label": "Shuffle Letter",
        "description": (
            "Adds the letter to the item pool and makes the letter cave a valid item placement destination.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 130,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "shuffle_major_shop_items": {
        "id": "shuffle_major_shop_items",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 24,
        "label": "Shuffle Major Shop Items",
        "description": (
            "Adds the wood arrows, blue candle, blue ring, and bait from shops A-D to the item pool. The second bait"
            "slot is replaced with a fairy for purchase and is not shuffled.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 140,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "shuffle_blue_potion": {
        "id": "shuffle_blue_potion",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 26,
        "label": "Shuffle Blue Potion",
        "description": (
            "Adds the blue potion from the potion shop to the item pool and makes the potion shop a valid item"
            "placement destination.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 150,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "progressive_items": {
        "id": "progressive_items",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 28,
        "label": "Progressive Items",
        "description": (
            "Makes swords, candles, arrows, and rings progressive. All items of each class become level-1 upgrades"
            "regardless of which shuffle flags are active. Picking up a level-1 item when you already own one"
            "increments your level in that class. If this flag is on but Shuffle Magical Sword is off, the magical"
            "sword cave still contains a sword upgrade. Random means the choice is made randomly at generation time.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 160,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "allow_important_in_l9": {
        "id": "allow_important_in_l9",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 10,
        "label": "Allow Important Items in Level 9",
        "description": (
            "By default the five logically critical items (ladder, raft, power bracelet, recorder, and bow) may not be"
            "placed in level 9. Enabling this removes that restriction.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 210,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "force_rr_to_l9": {
        "id": "force_rr_to_l9",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 14,
        "label": "Force Red Ring to Level 9",
        "description": (
            "Guarantees the red ring will only be found in level 9. Requires Shuffle Dungeon Items to be explicitly on"
            "(not random).\n"
        ),
        "group": "Item Shuffle",
        "display_order": 220,
        "default": "off",
        "depends_on": "shuffle_dungeon_items",
        "enabled": True,
        "phase": 1,
    },
    "force_sa_to_l9": {
        "id": "force_sa_to_l9",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 16,
        "label": "Force Silver Arrows to Level 9",
        "description": (
            "Guarantees silver arrows will only be found in level 9. Requires Shuffle Dungeon Items to be explicitly on"
            "(not random).\n"
        ),
        "group": "Item Shuffle",
        "display_order": 230,
        "default": "off",
        "depends_on": "shuffle_dungeon_items",
        "enabled": True,
        "phase": 1,
    },
    "white_sword_item": {
        "id": "white_sword_item",
        "type": "item",
        "bits": 5,
        "bit_offset": 30,
        "label": "White Sword Cave Item",
        "description": (
            "Controls the white sword cave location. Not Shuffled leaves it vanilla. Random adds it to the shuffle pool"
            "with no placement constraint. Selecting a specific item adds it to the pool and forces that item here. The"
            "selected item must be present in the active item pool.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 240,
        "default": "not_shuffled",
        "enabled": True,
        "phase": 1,
    },
    "armos_item": {
        "id": "armos_item",
        "type": "item",
        "bits": 5,
        "bit_offset": 35,
        "label": "Armos Item",
        "description": (
            "Controls the armos knights secret location (vanilla: power bracelet). Not Shuffled leaves it vanilla."
            "Random adds it to the shuffle pool with no placement constraint. Selecting a specific item adds it to the"
            "pool and forces that item here. The selected item must be present in the active item pool.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 250,
        "default": "not_shuffled",
        "enabled": True,
        "phase": 1,
    },
    "coast_item": {
        "id": "coast_item",
        "type": "item",
        "bits": 5,
        "bit_offset": 40,
        "label": "Coast Item",
        "description": (
            "Controls the coast location (vanilla: heart container). Not Shuffled leaves it vanilla. Random adds it to"
            "the shuffle pool with no placement constraint. Selecting a specific item adds it to the pool and forces"
            "that item here. Ladder cannot be selected — it is logically required to reach this location.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 260,
        "default": "not_shuffled",
        "enabled": True,
        "phase": 1,
    },
    "avoid_required_hard_combat": {
        "id": "avoid_required_hard_combat",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 47,
        "label": "Avoid Required Hard Combat",
        "description": (
            "When enabled, the logic engine requires the player to have at least one sword upgrade (white sword or"
            "better) AND one defense upgrade (blue or red ring) before considering hard enemies (blue wizzrobes, blue"
            "darknuts, gleeoks, patras) as defeatable. This makes seeds more accessible to casual players by ensuring"
            "difficult combat encounters are never logically required without adequate equipment.\n"
        ),
        "group": "Misc",
        "display_order": 210,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "randomize_dungeon_palettes": {
        "id": "randomize_dungeon_palettes",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 49,
        "label": "Randomize Dungeon Palettes",
        "description": (
            "Randomly assigns color palettes across all 9 dungeons. Each dungeon gets a randomized color theme drawn"
            "from 14 curated accent color schemes, while preserving structural fade and stairway palette sequences.\n"
        ),
        "group": "Misc",
        "display_order": 20,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "hint_mode": {
        "id": "hint_mode",
        "type": "enum",
        "bits": 3,
        "bit_offset": 51,
        "label": "Hint Mode",
        "description": (
            "Controls the style of hint text shown in caves and hint shops. Vanilla: no changes to hint text. Blank:"
            "all hint slots are set to blank. Community: random community quotes per slot. Helpful: gameplay-aware item"
            "location hints with community filler. Random: resolves to one of the above at generation time.\n"
        ),
        "group": "Misc",
        "display_order": 10,
        "default": "vanilla",
        "enabled": True,
        "phase": 1,
        "values": [
            {"id": "vanilla", "label": "Vanilla", "index": 0},
            {"id": "blank", "label": "Blank", "index": 1},
            {"id": "community", "label": "Community", "index": 2},
            {"id": "helpful", "label": "Helpful", "index": 3},
            {"id": "random", "label": "Random", "index": 4},
        ],
    },
    "randomize_bomb_upgrade": {
        "id": "randomize_bomb_upgrade",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 55,
        "label": "Randomize Bomb Upgrades",
        "description": (
            "Randomizes the bomb upgrade's cost (75-125 rupees) and the number of bombs added to your maximum (2-6)."
            "The on-screen price display is updated to match the randomized cost.\n"
        ),
        "group": "Caves and Shops",
        "display_order": 50,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "speed_up_dungeon_transitions": {
        "id": "speed_up_dungeon_transitions",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 71,
        "label": "Speed Up Dungeon Transitions",
        "description": (
            "Removes the scroll-delay loops during dungeon screen transitions, making room-to-room movement noticeably"
            "faster.\n"
        ),
        "group": "Quality of Life",
        "display_order": 30,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "speed_up_text": {
        "id": "speed_up_text",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 73,
        "label": "Speed Up Text",
        "description": "Reduces the text rendering delay so hint and shop text draws faster.\n",
        "group": "Quality of Life",
        "display_order": 20,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "extra_raft_blocks": {
        "id": "extra_raft_blocks",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 75,
        "label": "Extra Raft Blocks",
        "description": (
            "Converts the Westlake Mall and Casino Corner regions into raft-blocked areas, requiring the raft to access"
            "additional overworld screens.\n"
        ),
        "group": "Overworld",
        "display_order": 310,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "extra_power_bracelet_blocks": {
        "id": "extra_power_bracelet_blocks",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 77,
        "label": "Extra Power Bracelet Blocks",
        "description": (
            "Adds new power bracelet blocks in West Death Mountain. Intended for use with vanilla any road locations.\n"
        ),
        "group": "Overworld",
        "display_order": 320,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "randomize_lost_hills": {
        "id": "randomize_lost_hills",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 79,
        "label": "Randomize Lost Hills",
        "description": (
            "Randomizes the Lost Hills direction sequence and adds a hint NPC in the game. Requires Randomize Hints and"
            "Extended Hint Bank to be enabled.\n"
        ),
        "group": "Overworld",
        "display_order": 330,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "randomize_dead_woods": {
        "id": "randomize_dead_woods",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 81,
        "label": "Randomize Dead Woods",
        "description": (
            "Randomizes the Dead Woods direction sequence and adds a hint NPC in the game. Requires Randomize Hints and"
            "Extended Hint Bank to be enabled.\n"
        ),
        "group": "Overworld",
        "display_order": 340,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "update_recorder_warp_screens": {
        "id": "update_recorder_warp_screens",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 120,
        "label": "Update Recorder Warp Screens",
        "description": (
            "When enabled, recalculates the recorder warp destinations for levels 1-8 based on their shuffled overworld"
            "screen positions. The recorder warps Link to the screen one to the left of each dungeon entrance (the"
            "whirlwind scrolls him right automatically). Without this flag, the recorder always warps to vanilla"
            "screens regardless of entrance shuffle.\n"
        ),
        "group": "Overworld",
        "display_order": 110,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "add_extra_candles": {
        "id": "add_extra_candles",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 83,
        "label": "Add Extra Candles",
        "description": (
            "Adds a blue candle to the wood sword cave and a candle to the middle slot of the take-any cave."
            "Incompatible with Progressive Items.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 155,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "fast_fill": {
        "id": "fast_fill",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 85,
        "label": "Speed Up Heart Fill",
        "description": "Fill hearts faster from fairies and potions. (Patch courtesy of snarfblam.)\n",
        "group": "Quality of Life",
        "display_order": 10,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "flute_kills_pols": {
        "id": "flute_kills_pols",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 87,
        "label": "Recorder Kills Dungeon Pols Voice",
        "description": (
            "Play the recorder to kill all Pols Voice in dungeons. Does not work on the overworld. (Patch courtesy of"
            "Stratoform.)\n"
        ),
        "group": "Quality of Life",
        "display_order": 200,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "four_potion_inventory": {
        "id": "four_potion_inventory",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 91,
        "label": "Four Potion Inventory",
        "description": "Increases the potion inventory from 2 to 4 blue potions.\n",
        "group": "Quality of Life",
        "display_order": 110,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "auto_show_letter": {
        "id": "auto_show_letter",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 93,
        "label": "Auto Show Letter",
        "description": "Automatically shows the letter to NPCs without equipping and using it.\n",
        "group": "Quality of Life",
        "display_order": 100,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "like_like_rupees": {
        "id": "like_like_rupees",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 95,
        "label": "Like-Like Eats Rupees",
        "description": "Makes Like-Likes eat rupees instead of a magical shield.\n",
        "group": "Quality of Life",
        "display_order": 210,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "shuffle_shop_items": {
        "id": "shuffle_shop_items",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 114,
        "label": "Shuffle Shop Items",
        "description": (
            "Shuffles the 12 items across shops A-D, guaranteeing at least one major item per shop. Also jitters shop"
            "prices by ±20, and randomizes prices for the potion shop, secret caves, and door repair cave.\n"
        ),
        "group": "Caves and Shops",
        "display_order": 5,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "randomize_white_sword_hearts": {
        "id": "randomize_white_sword_hearts",
        "type": "bool",
        "bits": 1,
        "bit_offset": 97,
        "label": "Randomize White Sword Hearts",
        "description": "Randomizes the white sword cave heart requirement to between 4 and 6.\n",
        "group": "Caves and Shops",
        "display_order": 10,
        "default": False,
        "enabled": True,
        "phase": 1,
    },
    "randomize_magical_sword_hearts": {
        "id": "randomize_magical_sword_hearts",
        "type": "bool",
        "bits": 1,
        "bit_offset": 98,
        "label": "Randomize Magical Sword Hearts",
        "description": "Randomizes the magical sword cave heart requirement to between 10 and 12.\n",
        "group": "Caves and Shops",
        "display_order": 20,
        "default": False,
        "enabled": True,
        "phase": 1,
    },
    "permanent_sword_beam": {
        "id": "permanent_sword_beam",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 99,
        "label": "Permanent Sword Beam",
        "description": "Makes the sword beam fire at any health level, not just when hearts are full.\n",
        "group": "Misc",
        "display_order": 80,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "book_is_an_atlas": {
        "id": "book_is_an_atlas",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 101,
        "label": "Book Is An Atlas",
        "description": "Makes the Book of Magic function as an overworld atlas, displaying the map when used.\n",
        "group": "Misc",
        "display_order": 100,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "book_is_a_translator": {
        "id": "book_is_a_translator",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 105,
        "label": "Book Is A Translator",
        "description": (
            "Makes the Book of Magic function as a translator — old men's hint text is only shown when the player has"
            "the book.\n"
        ),
        "group": "Misc",
        "display_order": 110,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "visual_roar_sound": {
        "id": "visual_roar_sound",
        "type": "enum",
        "bits": 3,
        "bit_offset": 107,
        "label": "Visual Roar Sound",
        "description": (
            'Patches dungeon entry to display a beast sound above the level number instead of the vanilla "LIFE" label.'
            "OFF disables the patch entirely. RANDOM picks one of the six sounds at random each seed.\n"
        ),
        "group": "Misc",
        "display_order": 90,
        "default": "disabled",
        "enabled": True,
        "phase": 1,
        "values": [
            {"id": "disabled", "label": "Off", "index": 0},
            {"id": "roar", "label": "ROAR", "index": 1},
            {"id": "rawr", "label": "RAWR", "index": 2},
            {"id": "meow", "label": "MEOW", "index": 3},
            {"id": "woof", "label": "WOOF", "index": 4},
            {"id": "hiss", "label": "HISS", "index": 5},
            {"id": "honk", "label": "HONK", "index": 6},
            {"id": "random", "label": "Random", "index": 7},
        ],
    },
    "replace_book_fire_with_explosion": {
        "id": "replace_book_fire_with_explosion",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 110,
        "label": "Replace Book Fire with Explosion",
        "description": "Replaces the Book of Magic's fire projectile with a bomb explosion effect.\n",
        "group": "Misc",
        "display_order": 120,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "fix_known_bugs": {
        "id": "fix_known_bugs",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 112,
        "label": "Fix Known Bugs",
        "description": (
            "Applies a collection of vanilla ROM bug fixes: scrolling glitch, continue screen, enemy kill counter,"
            "enemy sprite rendering, quest mode check, enemy flash/pause routine, and sound engine fixes.\n"
        ),
        "group": "Quality of Life",
        "display_order": 80,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "cave_shuffle_mode": {
        "id": "cave_shuffle_mode",
        "type": "enum",
        "bits": 3,
        "bit_offset": 62,
        "label": "Cave Shuffle",
        "description": (
            "Controls which cave entrances are shuffled on the overworld. Vanilla: no shuffling. Dungeons Only: only"
            "dungeon (Level 1-9) entrances are shuffled. Non-Dungeons Only: only non-dungeon caves are shuffled. All"
            "Caves: both dungeon and non-dungeon entrances are shuffled.\n"
        ),
        "group": "Overworld",
        "display_order": 10,
        "default": "vanilla",
        "enabled": True,
        "phase": 2,
        "values": [
            {"id": "vanilla", "label": "Vanilla", "index": 0},
            {"id": "dungeons_only", "label": "Dungeons Only", "index": 1},
            {"id": "non_dungeons_only", "label": "Non-Dungeons Only", "index": 2},
            {"id": "all_caves", "label": "All Caves", "index": 3},
        ],
    },
    "include_wood_sword_cave": {
        "id": "include_wood_sword_cave",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 67,
        "label": "Include Wood Sword Cave",
        "description": (
            "When enabled, the wood sword cave entrance is included in the non-dungeon cave shuffle pool. Requires Cave"
            "Shuffle to include non-dungeon caves.\n"
        ),
        "group": "Overworld",
        "display_order": 20,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "include_any_road_caves": {
        "id": "include_any_road_caves",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 69,
        "label": "Include Any Road Caves",
        "description": (
            "When enabled, the Take Any Road cave entrances (normally power-bracelet gated) are included in the"
            "non-dungeon cave shuffle pool. Requires Cave Shuffle to include non-dungeon caves.\n"
        ),
        "group": "Overworld",
        "display_order": 30,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "shuffle_armos_location": {
        "id": "shuffle_armos_location",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 65,
        "label": "Shuffle Armos Screen",
        "description": "When enabled, randomizes which overworld screen the armos item appears on.\n",
        "group": "Overworld",
        "display_order": 130,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "randomize_mmg": {
        "id": "randomize_mmg",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 57,
        "label": "Randomize MMG",
        "description": (
            "Randomizes the prizes for the money making game. The two losing amounts are drawn from 1-20 rupees, the"
            "big-number trap from 30-50, and the two winning amounts from 10-30 and 25-75 respectively.\n"
        ),
        "group": "Caves and Shops",
        "display_order": 100,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "start_screen": {
        "id": "start_screen",
        "type": "enum",
        "bits": 2,
        "bit_offset": 60,
        "label": "Start Screen",
        "description": (
            "Controls which overworld screen Link starts on. Vanilla leaves the start screen unmodified. Easy Shuffle"
            "picks a random open screen, excluding all 44 special screens. Full Shuffle picks a random open screen,"
            "excluding only the base set. Wood Sword Screen places Link one row below the wood sword cave entrance.\n"
        ),
        "group": "Overworld",
        "display_order": 100,
        "default": "vanilla",
        "enabled": True,
        "phase": 2,
        "values": [
            {"id": "vanilla", "label": "Vanilla", "index": 0},
            {"id": "easy_shuffle", "label": "Easy Shuffle", "index": 1},
            {"id": "full_shuffle", "label": "Full Shuffle", "index": 2},
            {"id": "wood_sword_screen", "label": "Wood Sword Screen", "index": 3},
        ],
    },
    "add_l4_sword": {
        "id": "add_l4_sword",
        "type": "bool",
        "bits": 1,
        "bit_offset": 123,
        "label": "Add L4 Sword",
        "description": (
            "Adds an additional sword upgrade guarded by the level 9 triforce checker. Note that with a L4 sword, melee"
            "attacks will do L4 damage but beams do L3 damage. Only meaningful when Progressive Items is enabled.\n"
        ),
        "group": "Item Shuffle",
        "display_order": 80,
        "default": False,
        "enabled": True,
        "phase": 1,
    },
    "magical_boomerang_does_one_hp_damage": {
        "id": "magical_boomerang_does_one_hp_damage",
        "type": "bool",
        "bits": 1,
        "bit_offset": 122,
        "label": "Magical Boomerang Does 1 HP Damage",
        "description": (
            "Changes the magical boomerang to deal 1 HP of damage (equivalent to the wood sword) to enemies. Note that"
            "a boomerang may damage an enemy multiple times in one shot.\n"
        ),
        "group": "Misc",
        "display_order": 500,
        "default": False,
        "enabled": True,
        "phase": 1,
    },
    "shuffle_overworld_monsters": {
        "id": "shuffle_overworld_monsters",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 124,
        "label": "Shuffle Overworld Monsters",
        "description": (
            "Shuffles which enemies appear on the overworld, redistributing enemy types across overworld screens.\n"
        ),
        "group": "Enemies",
        "display_order": 10,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "shuffle_dungeon_monsters": {
        "id": "shuffle_dungeon_monsters",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 126,
        "label": "Shuffle Dungeon Monsters",
        "description": (
            "Shuffles dungeon monster assignments within each level using a constrained Fisher-Yates shuffle. Safety"
            "constraints prevent enemies from being placed in incompatible room types.\n"
        ),
        "group": "Enemies",
        "display_order": 20,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "shuffle_ganon_zelda": {
        "id": "shuffle_ganon_zelda",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 128,
        "label": "Shuffle Gannon and Zelda",
        "description": (
            "Includes the Gannon and Zelda rooms in the dungeon monster shuffle pool. Requires Shuffle Dungeon Monsters"
            "to be enabled.\n"
        ),
        "group": "Enemies",
        "display_order": 30,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "shuffle_level_9_monsters": {
        "id": "shuffle_level_9_monsters",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 130,
        "label": "Shuffle Level 9 Monsters",
        "description": (
            "Includes level 9 in the monster shuffle pools. Affects both within-level shuffling and between-levels"
            "shuffling.\n"
        ),
        "group": "Enemies",
        "display_order": 40,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "shuffle_monsters_between_levels": {
        "id": "shuffle_monsters_between_levels",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 132,
        "label": "Shuffle Monsters Between Levels",
        "description": (
            "Moves monster groups between dungeon levels. Enemies are categorized into tier-based pools and"
            "redistributed across levels.\n"
        ),
        "group": "Enemies",
        "display_order": 50,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "add_2nd_quest_monsters": {
        "id": "add_2nd_quest_monsters",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 134,
        "label": "Add 2nd Quest Monsters",
        "description": (
            "Merges 2nd quest enemy variants into the 1st quest enemy pools, adding more variety to the enemies"
            "encountered.\n"
        ),
        "group": "Enemies",
        "display_order": 60,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "enemy_hp": {
        "id": "enemy_hp",
        "type": "enum",
        "bits": 3,
        "bit_offset": 136,
        "label": "Enemy HP",
        "description": (
            "Controls enemy hit points. Normal leaves HP unchanged. +/-2 and +/-4 randomize each enemy's HP within that"
            "range. 0 HP sets all enemies to die in one hit. Random picks one of the other options at generation time.\n"
        ),
        "group": "Enemies",
        "display_order": 100,
        "default": "normal",
        "enabled": True,
        "phase": 2,
        "values": [
            {"id": "normal", "label": "Normal", "index": 0},
            {"id": "plus_minus_2", "label": "+/-2 HP", "index": 1},
            {"id": "plus_minus_4", "label": "+/-4 HP", "index": 2},
            {"id": "zero", "label": "0 HP", "index": 3},
            {"id": "random", "label": "Random", "index": 4},
        ],
    },
    "boss_hp": {
        "id": "boss_hp",
        "type": "enum",
        "bits": 3,
        "bit_offset": 139,
        "label": "Boss HP",
        "description": (
            "Controls boss hit points. Normal leaves HP unchanged. +/-2 and +/-4 randomize each boss's HP within that"
            "range. 0 HP sets all bosses to die in one hit. Random picks one of the other options at generation time.\n"
        ),
        "group": "Enemies",
        "display_order": 110,
        "default": "normal",
        "enabled": True,
        "phase": 2,
        "values": [
            {"id": "normal", "label": "Normal", "index": 0},
            {"id": "plus_minus_2", "label": "+/-2 HP", "index": 1},
            {"id": "plus_minus_4", "label": "+/-4 HP", "index": 2},
            {"id": "zero", "label": "0 HP", "index": 3},
            {"id": "random", "label": "Random", "index": 4},
        ],
    },
    "ganon_hp_to_zero": {
        "id": "ganon_hp_to_zero",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 142,
        "label": "Set Gannon HP to 0",
        "description": (
            "Sets Gannon's HP to 0, making the final boss die in one hit regardless of the Boss HP setting.\n"
        ),
        "group": "Enemies",
        "display_order": 120,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "shuffle_enemy_groups": {
        "id": "shuffle_enemy_groups",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 144,
        "label": "Shuffle Enemy Groups",
        "description": (
            "Shuffles which enemies appear in each dungeon's sprite group, changing the enemy roster for each dungeon"
            "level.\n"
        ),
        "group": "Enemies",
        "display_order": 70,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "shuffle_bosses": {
        "id": "shuffle_bosses",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 146,
        "label": "Shuffle Bosses",
        "description": (
            "Assigns a random boss difficulty tier to each dungeon level, then replaces boss enemies with random picks"
            "from the assigned tier's pool. Earlier dungeons are biased toward easier bosses.\n"
        ),
        "group": "Enemies",
        "display_order": 80,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "change_dungeon_boss_groups": {
        "id": "change_dungeon_boss_groups",
        "type": "tristate",
        "bits": 2,
        "bit_offset": 148,
        "label": "Change Dungeon Boss Groups",
        "description": (
            "Redistributes which bosses belong to which sprite-set group (A/B/C), then replaces every existing boss"
            "room with a random pick from its group's new pool.\n"
        ),
        "group": "Enemies",
        "display_order": 90,
        "default": "off",
        "enabled": True,
        "phase": 2,
    },
    "select_swap_mode": {
        "id": "select_swap_mode",
        "type": "enum",
        "bits": 2,
        "cosmetic_bit_offset": 0,
        "cosmetic": True,
        "label": "SELECT Button Item Swap",
        "description": (
            "Controls whether the SELECT button can switch the equipped B-button item while paused. Pause: vanilla"
            "behavior, SELECT opens the pause menu as normal. Swap: pressing SELECT while paused jumps directly to item"
            "slot 7. Toggle: pressing SELECT while paused cycles between two item pages, with SWAP/PAUSE labels"
            "rendered on the pause menu.\n"
        ),
        "group": "Cosmetic",
        "display_order": 10,
        "default": "pause",
        "enabled": True,
        "phase": 1,
        "values": [
            {"id": "pause", "label": "Pause (Vanilla)", "index": 0},
            {"id": "swap", "label": "Swap", "index": 1},
            {"id": "toggle", "label": "Toggle", "index": 2},
        ],
    },
    "deathwarp_button": {
        "id": "deathwarp_button",
        "type": "enum",
        "bits": 2,
        "cosmetic_bit_offset": 2,
        "cosmetic": True,
        "label": "Deathwarp Buttons",
        "description": (
            "Controls which controller and button combination triggers a deathwarp. Vanilla: Up + A on the second"
            "controller. P1 Up+A: Up + A on the first controller. P1 Up+Select: Up + SELECT on the first controller.\n"
        ),
        "group": "Cosmetic",
        "display_order": 20,
        "default": "p2_up_a",
        "enabled": True,
        "phase": 1,
        "values": [
            {"id": "p2_up_a", "label": "P2 Up+A (Vanilla)", "index": 0},
            {"id": "p1_up_a", "label": "P1 Up+A", "index": 1},
            {"id": "p1_up_sel", "label": "P1 Up+Select", "index": 2},
        ],
    },
    "low_hearts_sound": {
        "id": "low_hearts_sound",
        "type": "enum",
        "bits": 2,
        "cosmetic_bit_offset": 4,
        "cosmetic": True,
        "label": "Low Health Beep",
        "description": (
            "Controls the low hearts sound. Regular: vanilla beep sound. Softer: a softer heartbeat sound. (Patch"
            "courtesy of gzip.) Disabled: removes the low hearts sound entirely.\n"
        ),
        "group": "Cosmetic",
        "display_order": 100,
        "default": "regular",
        "enabled": True,
        "phase": 1,
        "values": [
            {"id": "regular", "label": "Regular (Vanilla)", "index": 0},
            {"id": "softer", "label": "Softer", "index": 1},
            {"id": "disabled", "label": "Disabled", "index": 2},
        ],
    },
    "disable_music": {
        "id": "disable_music",
        "type": "tristate",
        "bits": 2,
        "cosmetic_bit_offset": 6,
        "cosmetic": True,
        "label": "Disable Music",
        "description": "Silences all game music by zeroing out the music track table. Sound effects are unaffected.\n",
        "group": "Cosmetic",
        "display_order": 101,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "reduce_flashing": {
        "id": "reduce_flashing",
        "type": "tristate",
        "bits": 2,
        "cosmetic_bit_offset": 13,
        "cosmetic": True,
        "label": "Reduce Flashing",
        "description": (
            "Removes the triforce collection flash effect, reducing potentially seizure-inducing flashing.\n"
        ),
        "group": "Cosmetic",
        "display_order": 103,
        "default": "off",
        "enabled": True,
        "phase": 1,
    },
    "level_name": {
        "id": "level_name",
        "type": "enum",
        "bits": 5,
        "cosmetic_bit_offset": 8,
        "cosmetic": True,
        "label": "Level Name",
        "description": (
            'Changes the dungeon HUD label from "LEVEL-1" to an alternative name. Random Choice picks one of the'
            "options at random each seed.\n"
        ),
        "group": "Cosmetic",
        "display_order": 102,
        "default": "level",
        "enabled": True,
        "phase": 1,
        "values": [
            {"id": "level", "label": "LEVEL (Vanilla)", "index": 0},
            {"id": "random_choice", "label": "Random Choice", "index": 1},
            {"id": "abode", "label": "ABODE", "index": 2},
            {"id": "act", "label": "ACT", "index": 3},
            {"id": "area", "label": "AREA", "index": 4},
            {"id": "asylum", "label": "ASYLUM", "index": 5},
            {"id": "board", "label": "BOARD", "index": 6},
            {"id": "cage", "label": "CAGE", "index": 7},
            {"id": "camp", "label": "CAMP", "index": 8},
            {"id": "cave", "label": "CAVE", "index": 9},
            {"id": "corral", "label": "CORRAL", "index": 10},
            {"id": "lair", "label": "LAIR", "index": 11},
            {"id": "palace", "label": "PALACE", "index": 12},
            {"id": "place", "label": "PLACE", "index": 13},
            {"id": "random_name", "label": "RANDOM", "index": 14},
            {"id": "realm", "label": "REALM", "index": 15},
            {"id": "region", "label": "REGION", "index": 16},
            {"id": "sector", "label": "SECTOR", "index": 17},
            {"id": "sphere", "label": "SPHERE", "index": 18},
            {"id": "stage", "label": "STAGE", "index": 19},
            {"id": "temple", "label": "TEMPLE", "index": 20},
            {"id": "world", "label": "WORLD", "index": 21},
            {"id": "zone", "label": "ZONE", "index": 22},
        ],
    },
    "green_tunic_color": {
        "id": "green_tunic_color",
        "type": "color",
        "bits": 6,
        "cosmetic_bit_offset": 15,
        "cosmetic": True,
        "label": "Green Tunic Color",
        "description": (
            "Changes the starting (green) tunic color. Vanilla is the original green. Random picks from a curated set"
            "of colors each seed.\n"
        ),
        "group": "Cosmetic",
        "display_order": 200,
        "default": 0,
        "enabled": True,
        "phase": 1,
    },
    "blue_ring_color": {
        "id": "blue_ring_color",
        "type": "color",
        "bits": 6,
        "cosmetic_bit_offset": 21,
        "cosmetic": True,
        "label": "Blue Ring Color",
        "description": (
            "Changes the blue ring tunic color. Vanilla is the original blue. Random picks from a curated set of colors"
            "(different from the start tunic).\n"
        ),
        "group": "Cosmetic",
        "display_order": 210,
        "default": 0,
        "enabled": True,
        "phase": 1,
    },
    "red_ring_color": {
        "id": "red_ring_color",
        "type": "color",
        "bits": 6,
        "cosmetic_bit_offset": 27,
        "cosmetic": True,
        "label": "Red Ring Color",
        "description": (
            "Changes the red ring tunic color. Vanilla is the original red. Random picks from a curated set (different"
            "from start tunic and blue ring).\n"
        ),
        "group": "Cosmetic",
        "display_order": 220,
        "default": 0,
        "enabled": True,
        "phase": 1,
    },
    "heart_color": {
        "id": "heart_color",
        "type": "color",
        "bits": 6,
        "cosmetic_bit_offset": 33,
        "cosmetic": True,
        "label": "Heart HUD Color",
        "description": (
            "Changes the heart color in the dungeon HUD. Vanilla is the original red. Random picks from a curated set"
            "of colors each seed.\n"
        ),
        "group": "Cosmetic",
        "display_order": 230,
        "default": 0,
        "enabled": True,
        "phase": 1,
    },
}

_ITEM_ENUM: list[dict[str, Any]] = [
    {"id": "random", "index": 0, "label": "Random"},
    {"id": "wood_sword", "index": 1, "label": "Wood Sword"},
    {"id": "white_sword", "index": 2, "label": "White Sword"},
    {"id": "magical_sword", "index": 3, "label": "Magical Sword"},
    {"id": "wood_arrows", "index": 4, "label": "Wood Arrows"},
    {"id": "silver_arrows", "index": 5, "label": "Silver Arrows"},
    {"id": "bow", "index": 6, "label": "Bow"},
    {"id": "blue_candle", "index": 7, "label": "Blue Candle"},
    {"id": "red_candle", "index": 8, "label": "Red Candle"},
    {"id": "blue_ring", "index": 9, "label": "Blue Ring"},
    {"id": "red_ring", "index": 10, "label": "Red Ring"},
    {"id": "power_bracelet", "index": 11, "label": "Power Bracelet"},
    {"id": "ladder", "index": 12, "label": "Ladder"},
    {"id": "raft", "index": 13, "label": "Raft"},
    {"id": "recorder", "index": 14, "label": "Recorder"},
    {"id": "magical_key", "index": 15, "label": "Magical Key"},
    {"id": "boomerang", "index": 16, "label": "Boomerang"},
    {"id": "magical_boomerang", "index": 17, "label": "Magical Boomerang"},
    {"id": "wand", "index": 18, "label": "Wand"},
    {"id": "letter", "index": 19, "label": "Letter"},
    {"id": "bait", "index": 20, "label": "Bait"},
    {"id": "blue_potion", "index": 21, "label": "Blue Potion"},
    {"id": "heart_container", "index": 22, "label": "Heart Container"},
    {"id": "not_shuffled", "index": 31, "label": "Not Shuffled"},
]


# ===========================================================================
# ITEM POOL COMPUTATION
# ===========================================================================

# Maps flag id → items it adds to the pool when resolved to ON
_POOL_CONTRIBUTIONS: dict[str, list[str]] = {
    "shuffle_dungeon_items": [
        "bow", "boomerang", "magical_boomerang", "raft", "ladder",
        "recorder", "wand", "red_candle", "magical_key",
        "silver_arrows", "red_ring",
        # TODO: confirm "book_of_magic" item_enum id with data_model.py
    ],
    "shuffle_dungeon_hearts": ["heart_container"],  # adds 8
    "shuffle_letter": ["letter"],
    "shuffle_wood_sword": ["wood_sword"],
    "shuffle_magical_sword": ["magical_sword"],
    "shuffle_major_shop_items": ["wood_arrows", "blue_candle", "blue_ring", "bait"],
    "shuffle_blue_potion": ["blue_potion"],
}


def compute_active_pool(flags: Flags) -> set[str]:
    """Return the set of item ids currently in the shuffle pool.

    Call this on fully-resolved flags (after resolve_random_flags).
    Random tristate values are treated as OFF for pool computation.
    """
    pool: set[str] = set()
    for flag_id, items in _POOL_CONTRIBUTIONS.items():
        value = getattr(flags, flag_id, Tristate.OFF)
        if value == Tristate.ON:
            pool.update(items)
    # The coast location contains a heart container in vanilla.
    # When coast_item is shuffled (anything other than NOT_SHUFFLED),
    # that heart container enters the pool regardless of shuffle_dungeon_hearts.
    not_shuffled_index = next(e["index"] for e in _ITEM_ENUM if e["id"] == "not_shuffled")
    if int(flags.coast_item) != not_shuffled_index:
        pool.add("heart_container")
    return pool


# ===========================================================================
# RANDOM FLAG RESOLUTION
# ===========================================================================

# Dependency graph: maps flag_id → list of flag_ids that depend on it
_DEPENDENTS: dict[str, list[str]] = {
    "shuffle_dungeon_items": ["shuffle_dungeon_hearts", "force_rr_to_l9", "force_sa_to_l9"],
    "shuffle_within_dungeons": ["allow_triforces_in_stairways"],
}


def resolve_random_flags(flags: Flags, rng: Rng) -> Flags:
    """Resolve all RANDOM tristate values to ON or OFF.

    Resolution is performed in dependency order: prerequisites are resolved
    before dependents. If a prerequisite resolves to OFF, all dependent
    flags cascade to OFF regardless of their own setting.

    Args:
        flags: Flags instance (may contain Tristate.RANDOM values)
        rng:   random.Random instance (or compatible) for coin flips
    Returns:
        New Flags instance with all tristate values resolved to ON or OFF.
    """
    import copy
    resolved = copy.copy(flags)

    # Topological order: process parents before children.
    # Simple approach: iterate until stable (safe for shallow graphs).
    changed = True
    while changed:
        changed = False
        for flag_id, offset, width in _FLAG_LAYOUT:
            flag_def = _FLAG_DEFS[flag_id]
            if flag_def["type"] != "tristate":
                continue
            if not flag_def.get("enabled", True):
                continue  # skip disabled flags
            current = getattr(resolved, flag_id)
            if current != Tristate.RANDOM:
                continue
            # Check if this flag's prerequisite has been resolved
            dep = flag_def.get("depends_on")
            if dep:
                dep_value = getattr(resolved, dep)
                if dep_value == Tristate.OFF:
                    # Cascade: prerequisite is off, force this flag off
                    object.__setattr__(resolved, flag_id, Tristate.OFF)
                    changed = True
                    continue
                if dep_value == Tristate.RANDOM:
                    # Prerequisite not yet resolved; skip for now
                    continue
            # Resolve randomly
            flipped = Tristate.ON if rng.random() < 0.5 else Tristate.OFF
            object.__setattr__(resolved, flag_id, flipped)
            changed = True
    return resolved


# ===========================================================================
# SCHEMA VERSION CHECK
# ===========================================================================

SCHEMA_VERSION = 1
SCHEMA_HASH = "7fa68d322faa7d9d"
