"""Progressive-items patches as bytes (docs/progressive-patches.md).

Generated by `python3 asm/progressive/build.py build` from asm/fp-prog-0*/;
do not edit. PATCHES[name] is a tuple of (file offset, piece) writes, against
ZORA's code patches (asm/series.txt) with the patches before it applied:
fp-prog-01, then fp-prog-02. A piece is ZORA's own bytes or an Original
(source, length), read from the player's ROM when written.
"""
from zora.rom.base_rom import Original, Piece

PATCHES: dict[str, tuple[tuple[int, Piece], ...]] = {
    "fp-prog-01": (
        (0x04658, bytes.fromhex("205fbe")),
        (0x04920, bytes.fromhex("a5be")),
        (0x07E50, bytes.fromhex("0100000000ffff01020304ad500338e974a8a9ffc007b003b944be8502a8608d13048a48204bbea202"
                                "a4023008b9bee63d7706d014bd2204293f20e0be901d8503a402300da501f009a9009d3004a93f8503"
                                "bd220429c005039d2204ca10ca68aaad130460200c73204bbe300eb9bee63d41bef0061d77069d7706"
                                "60")),
        (0x07EF0, bytes.fromhex("ac40bed00218608500c91fb03de91cc902902aa400b9a4728501b9c87238e920c910b02649ff386500"
                                "a40138795706a8b9a47245018501f00188983860ad75068501ad740618691d3860a5001860")),
    ),
    "fp-prog-02": (
        (0x10D06, bytes.fromhex("20c7b4eaea")),
        (0x13490, bytes.fromhex("8500c91fb03de91cc902902aa400b9a4728501b9c87238e920c910b02649ff386500a40138795706a8"
                                "b9a47245018501f00188983860ad75068501ad740618691d3860a5001860a8a50148a50048982080b4"
                                "85ab6885006885014c1473")),
        (0x17864, bytes.fromhex("2087baeaea")),
        (0x1789B, bytes.fromhex("20a7baea")),
        (0x17A50, bytes.fromhex("8500c91fb03de91cc902902aa400b9a4728501b9c87238e920c910b02649ff386500a40138795706a8"
                                "b9a47245018501f00188983860ad75068501ad740618691d3860a5001860cd4fb8f015a8a50148a500"
                                "48982040baa868850068850198a4eb85abb9fe6a60a8a50148a50048982040ba85ab688500688501a9"
                                "c060")),
    ),
}

# Data written per seed: exported label -> file offset.
SYMBOLS: dict[str, int] = {
    "ZORA_B1_OneTimeWares": 0x07E51,
    "ZORA_B1_ProgressiveItems": 0x07E50,
}

# ResolveProgressive's shared body in each bank: (first file offset, end), end exclusive.
RESOLVE_COPIES: dict[int, tuple[int, int]] = {
    1: (0x07EF7, 0x07F3E),
    4: (0x13490, 0x134D7),
    5: (0x17A50, 0x17A97),
}

# The operand bank 5's room hook reads as the "no item" code (CreateRoomObjects + 21).
NOTHING_CODE_OPERAND = 0x1785F
