"""The registry: every checkpoint in table order (CHECKPOINTS) and
measure_rom, which measures them all on one finished ROM."""
from typing import Any

from zora.model.enums import BossSpriteSet, RoomType, Side
from zora.model.game_world import GameWorld
from zora_measure.checkpoints.acceptance import (
    BOW_LIST,
    BOW_LIST_ITEMS,
    LONG_ITEMS,
    PLACE_KEYS,
    RATIOS,
    RECORDER_LIST,
    RECORDER_LIST_ITEMS,
    SPEC_B6,
    SPEC_E1,
    SPLIT_SUMMARY,
    SWORD_LIST,
    SWORD_LIST_ITEMS,
    e1_replay,
    items_in_list_rooms,
    long_item_level,
    long_item_split,
    long_items_outside_level9,
    self_locks,
    tracked_in_level9,
)
from zora_measure.checkpoints.dungeon_room_shuffle import (
    GANON_LAYOUT,
    LEVEL1_ARRIVING_LAYOUTS,
    LEVEL9_PERSON_SIDE_KEYS,
    LEVEL9_PERSON_TRIGGER_KEYS,
    ROMS_PER_LEVEL,
    ZELDA_NEIGHBOUR_COUNTS,
    level1_arriving_layouts,
    level9_cellar_progression,
    level9_person_any_shutter,
    level9_person_sides,
    level9_person_trigger,
    level9_room_progression,
    levels_with_layout,
    zelda_neighbour_count,
    zelda_neighbours_trigger3,
)
from zora_measure.checkpoints.dungeon_text import (
    HELPFUL_LEVEL_COUNTS,
    HINT_CENSUS_SPEC,
    HINT_CODES,
    UNHELPFUL_ROOM_COUNTS,
    _flagged_list,
    helpful_level_count,
    hint_streams_hold,
    kept_bomb_upgrade_rooms,
    unhelpful_room_count,
)
from zora_measure.checkpoints.features import (
    B10_BOMB_SUMMARY,
    B10_CREDITS_SUMMARY,
    B10_MMG_SUMMARY,
    B10_SWORD_SUMMARY,
    B10_TITLE_SUMMARY,
    SPEC_B10,
    SPEC_B10_F10,
    SUMMED_COUNTS,
    b10_bomb_upgrade,
    b10_constants,
    b10_credits_locked,
    b10_level9_refusal,
    b10_mmg_amounts,
    b10_start_state,
    b10_sword_hearts,
    b10_title,
    dungeon_arrival_codes,
    exit_room_count_zero,
    person_appearances,
)
from zora_measure.checkpoints.groups_and_palettes import (
    BOSS_IDENTITIES,
    GORIYA_TILES,
    OPEN_MOUTH_VALUES,
    _b1,
    any_overworld_enemy_in_dungeon,
    boss_blocks,
    boss_identities,
    boss_placement,
    color_sets_check,
    fixed_frame_bytes,
    goriya_seed_slot,
    goriya_tile,
    hearts_total,
    inner_selector_shares,
    item_carriers_off,
    mixed_list_checks,
    one_headed_gleeoks,
    open_mouth,
    overworld_enemy_shares,
    partner_runs,
    partner_runs_changed,
    zol_rooms_with_bit_7,
)
from zora_measure.checkpoints.hint_text import (
    EXPECTED_OFFER_SELECTORS,
    LOCATION_SUMMARY,
    NAME_SUMMARY,
    REQUIREMENT_SUMMARY,
    SPEC_HINT,
    TRIO_SUMMARY,
    _hint_record,
    _inside_dungeon_summary,
    _text_kind_summary,
    _white_sword_hint_summary,
    hint_shop_offer_selectors,
    hint_shop_prices,
    underworld_selector_tables,
)
from zora_measure.checkpoints.monster_passes import (
    CENSUS_FLAGGED_SPEC,
    CENSUS_LAYOUT_BYTES,
    CENSUS_PERSONS_SPEC,
    CENSUS_SPEC,
    PER_LEVEL_SUMMARY,
    TIER_MIXES,
    TIER_SUMMARY,
    _layout_byte_is,
    boss_bank_tiers,
    boss_bar_violations,
    census_by_level,
    enemy_bank_tiers,
    enemy_tier_mix,
    ganon_room_item_and_trigger,
    monster_bar_violations,
    zelda_on_barred_layout,
)
from zora_measure.checkpoints.overworld import (
    ARMOS_FIRST_SCREENS,
    EXTRA_PRICE_SUMMARY,
    SPEC_OW,
    START_SCREEN_SPREAD,
    START_Y_VALUES,
    any_road_array,
    any_road_position_index,
    armos_first_screen,
    armos_tables,
    code_screen_counts,
    destinations_changed,
    door_counts_match,
    dungeons_on_prg0_door,
    entries_keeping_code,
    extra_candles,
    extra_prices,
    extra_prices_in_range,
    neither_quest_bytes,
    recorder_distinct_screens,
    recorder_follows_doors,
    screen36_f,
    shop_front_doors,
    shop_prices,
    shop_stock,
    start_room_ban,
    start_screen,
    start_screen_rules,
    start_y_value,
    sword_and_any_road_counts,
    unenrolled_screens_kept,
    vacated_screen_kept,
    wood_sword_screen,
)
from zora_measure.checkpoints.overworld_monsters_and_hp import (
    GLEEOK_HEAD_VALUES,
    HP_WALK_SUMMARY,
    SPEC_B8,
    boss_hp_walk,
    enemy_hp_walk,
    gleeok_head_hp,
    level9_records_match,
    owm_no_barred_placement,
    owm_non_candidates_kept,
    owm_screens,
    screen_119_layout_kept,
    start_screen_takes_119s_pair,
    wizzrobe_overworld_patch,
)
from zora_measure.checkpoints.shapes_and_gate import (
    ABSENT_SUMMARY,
    BOMB_SUMMARY,
    COST_SUMMARY,
    DOOR_MIX_SUMMARY,
    LAST_BOSS_ROOM_ITEM_KEYS,
    LATER_LEVEL_SIZES,
    LEVEL1_SIZES,
    LEVEL9_PIECE_KEYS,
    LEVEL9_STAIRCASE_KEYS,
    MAP_TRIGGER_KEYS,
    PAIR_SUMMARY,
    PERSON_LIST_SUMMARY,
    PUSH_EXEMPT_LAYOUTS,
    TOLL_PAIRS,
    UNOWNED_BINS,
    absent_items,
    bomb_operands,
    by_count_index,
    cellar_items_on_the_ledge,
    corner_unowned,
    door_side_mix,
    ganon_on_own_layout,
    item_trigger7_level9,
    item_trigger7_levels_1_8,
    last_boss_room_compass,
    last_boss_room_items,
    layout_27_south_open,
    layout_bytes,
    level1_person_lists,
    level1_persons,
    level9_entrance_north_open,
    level9_entrance_side_pairs,
    level9_map_trigger,
    level9_person_above_entrance,
    level9_person_shuttered,
    level9_pieces,
    level9_plain_0b_rooms,
    level9_staircases,
    level_sizes,
    minimap_stale_tails,
    per_thousand_by_code,
    per_thousand_by_key,
    person_north_pairs,
    pin_pairs,
    push_rooms_7_9,
    room_palettes,
    stair_exits_in_level,
    toll_costs,
    toll_pair,
    transport_exits_differ,
    trigger3_rooms_exact,
    unowned_bin,
    unowned_blank,
    unowned_count,
    unowned_off_bottom_row,
    unowned_on_six_level_grid,
    zelda_neighbour_push,
    zelda_on_own_layout,
    zelda_side_shuttered,
)
from zora_measure.checkpoints.summaries import (
    FLAG_COUNTS,
    SPEC_B1,
    SPEC_B2,
    SPEC_B3,
    SPEC_B4,
    SPEC_B5,
    SPEC_B25,
    SPEC_GATE,
    SPEC_GATE_19,
    SPEC_GATE_20,
    SPEC_SHAPES,
    SPEC_SHAPES_U30,
    Checkpoint,
    count_true,
    distribution,
    mean_of,
    per_thousand_roms,
    ratio_total,
)
from zora_measure.hint_information import BLANK, COMPOSED, GREETING, POOL_TEXT, SHOWN_SLOTS
from zora_measure.statistics import b1_checkpoint

CHECKPOINTS: tuple[Checkpoint, ...] = (
    Checkpoint("SH-GRID-17", "unowned cells per ROM, mean", "1.042", SPEC_SHAPES,
               unowned_count, mean_of()),
    Checkpoint("SH-GRID-01", "ROMs with 1 / 2 / 3-6 / 7+ unowned cells", "not bounded (corpus 971/23/6/0)",
               SPEC_SHAPES, unowned_bin, distribution(UNOWNED_BINS)),
    Checkpoint("SH-GRID-16", "ROMs with exactly one unowned cell", "971/1000", SPEC_SHAPES,
               lambda gw: unowned_count(gw) == 1, count_true),
    Checkpoint("SH-GRID-16", "levels 7-9 corner cell $7F unowned", "415/1000", SPEC_SHAPES,
               corner_unowned, count_true),
    Checkpoint("SH-GRID-16", "unowned cells on the six-level grid, total", "40 (in 27/1000 ROMs)",
               SPEC_SHAPES, unowned_on_six_level_grid, per_thousand_roms),
    Checkpoint("SH-GRID-16", "unowned cells off the bottom row, total", "184", SPEC_SHAPES,
               unowned_off_bottom_row, per_thousand_roms),
    Checkpoint("SH-MAP-01", "levels with vanilla bytes past the minimap terminator",
               "not stated (corpus: 11 in 9,000 levels)", SPEC_SHAPES, minimap_stale_tails,
               per_thousand_roms),
    Checkpoint("SH-GRID-07", "level 9: one piece / two, small one room / two, small 2+ / three+",
               "not stated (measured: two pieces in 26/1000 corpus ROMs, 79/3000 seeds; "
               "small piece one room in 63/79)", SPEC_SHAPES, level9_pieces, distribution(LEVEL9_PIECE_KEYS)),
    Checkpoint("SH-STAIR-02", "level 9 (pieces, transports, item cellars): (1, 6, 2) / (2, 7, 2)",
               "every ROM one of the two (measured, 3,000 seeds)", SPEC_SHAPES, level9_staircases,
               distribution(LEVEL9_STAIRCASE_KEYS)),
    Checkpoint("SH-STAIR-16", "every item cellar's item at position $89 (the upper ledge), transports $00",
               "1000/1000 (measured; spec text pending review)", SPEC_SHAPES, cellar_items_on_the_ledge,
               count_true),
    Checkpoint("SH-GRID-17", "unowned cells carrying the blank room", "1042/1042", SPEC_SHAPES,
               unowned_blank, ratio_total),
    Checkpoint("SH-GRID-14", "level-1 rooms min / mean / max", "11 / 14.4 / 19", SPEC_SHAPES,
               level_sizes, LEVEL1_SIZES),
    Checkpoint("SH-GRID-14", "rooms per level, mean, L2-L9",
               "15.8 17.3 19.2 22.0 30.2 29.7 36.4 47.5", SPEC_SHAPES,
               level_sizes, LATER_LEVEL_SIZES),
    Checkpoint("PS-GRUM-02", "ROMs with exactly one hungry goriya", "1000/1000", SPEC_B1,
               lambda gw: b1_checkpoint(gw).goriya == 1, count_true),
    Checkpoint("B1 checkpoint", "ROMs with exactly one $8E item byte", "1000/1000", SPEC_B1,
               lambda gw: b1_checkpoint(gw).ganon_8e == 1, count_true),
    Checkpoint("PS-MERCH-01", "merchants 1 / 2 / 3", "334/343/323", SPEC_B1,
               _b1("merchants"), distribution((1, 2, 3))),
    Checkpoint("PS-ITEM-02", "ROMs with 9 heart containers", "1000/1000", SPEC_B1,
               lambda gw: hearts_total(gw) == 9, count_true),
    Checkpoint("PS-ITEM-02", "dungeon hearts 6 / 7 / 8 / 9", "44/252/471/233", SPEC_B1,
               _b1("hearts_dungeon"), distribution((6, 7, 8, 9))),
    Checkpoint("PS-ITEM-02", "dungeon hearts, mean", "7.89", SPEC_B1,
               _b1("hearts_dungeon"), mean_of("{:.2f}")),
    Checkpoint("PS-ITEM-03", "pool items absent from the dungeons (range over 12)",
               "11.9-15.2%", SPEC_B1, absent_items, ABSENT_SUMMARY),
    Checkpoint("B1 checkpoint", "level-1 person rooms 0 / 1", "66/934", SPEC_B1,
               level1_persons, distribution((0, 1))),
    Checkpoint("B1 checkpoint", "level-1 person lists $0B-$11",
               "201/243/146/92/133/10/109", SPEC_B1,
               level1_person_lists, PERSON_LIST_SUMMARY),
    Checkpoint("PS-MERCH-04", "toll pairs MB/keys, life/keys, MB/money, life/money, life/MB",
               "226/208/196/191/179", SPEC_B1, toll_pair, distribution(TOLL_PAIRS)),
    Checkpoint("PS-MERCH-04", "toll costs",
               "keys 43.4%, cost 131/156/147; money 30-70, mean 49.6", SPEC_B1,
               toll_costs, COST_SUMMARY),
    Checkpoint("PS-BOMB-03", "branch patched / operands name $0F levels / same level twice",
               "1000/1000 / 1000/1000 / 111/1000", SPEC_B1, bomb_operands, BOMB_SUMMARY),
    Checkpoint("VA-REJ-03 step 6", "levels 7-9 push rooms by layout byte",
               "$5A 3872 $60 1980 $DA 1429", SPEC_GATE, push_rooms_7_9,
               per_thousand_by_code(PUSH_EXEMPT_LAYOUTS)),
    Checkpoint("A39", "level-9 $4B room with trigger 0 and a shutter side", "415/1000",
               SPEC_GATE, level9_person_shuttered, count_true),
    Checkpoint("VA-REJ-03 step 3", "level-9 $4B room directly above the entrance",
               "1000/1000", SPEC_GATE, level9_person_above_entrance, count_true),
    Checkpoint("VA-REJ-03", "stair exits inside their level, not the entrance",
               "22588/22588", SPEC_GATE, stair_exits_in_level, ratio_total),
    Checkpoint("VA-REJ-03", "transport exits that differ", "12588/12588", SPEC_GATE,
               transport_exits_differ, ratio_total),
    Checkpoint("A33", "non-Ganon trigger-3 rooms with trigger byte exactly $03",
               "1717/1717", SPEC_GATE, trigger3_rooms_exact, ratio_total),
    Checkpoint("A32", "Zelda-neighbour trigger-3 rooms keeping a push block",
               "$5A 134 $60 57 $DA 53", SPEC_GATE, zelda_neighbour_push,
               per_thousand_by_code(PUSH_EXEMPT_LAYOUTS)),
    Checkpoint("A3", "ROMs with a shuttered Zelda side", "0/1000", SPEC_GATE,
               zelda_side_shuttered, count_true),
    Checkpoint("A25", "layout bytes $9B / $8E / $8F / $92 / $A7 / $8B",
               "$9B 1857 $8E 275 $8F 253 $92 273 $A7 274 $8B 116", SPEC_GATE, layout_bytes,
               per_thousand_by_code((0x9B, 0x8E, 0x8F, 0x92, 0xA7, 0x8B))),
    Checkpoint("VA-REJ-01", "layout byte $E0 rooms", "$E0 0", SPEC_GATE, layout_bytes,
               per_thousand_by_code((0xE0,))),
    Checkpoint("A34", "level-9 non-person $0B rooms / with the count bit ($8B)", "227 / 187",
               SPEC_GATE, level9_plain_0b_rooms, by_count_index((0, 2))),
    Checkpoint("pin table", "layout-$27 rooms' N / E / W wall/wall pairs",
               "563/563 633/633 579/579",
               SPEC_GATE, lambda gw: {side.name.lower(): pin_pairs(gw, RoomType.ZELDA_ROOM, (side,))
                                      for side in (Side.NORTH, Side.EAST, Side.WEST)},
               PAIR_SUMMARY),
    Checkpoint("pin table", "ROMs whose layout-$27 rooms' south sides are not walls",
               "1000/1000", SPEC_GATE, layout_27_south_open, count_true),
    Checkpoint("pin table", "$1B rooms' east wall/wall pairs", "3572/3572", SPEC_GATE,
               lambda gw: pin_pairs(gw, RoomType.NARROW_STAIR_ROOM, (Side.EAST,)),
               ratio_total),
    Checkpoint("pin table", "level-9 entrance E / W wall/wall pairs",
               '803/803 804/804 (stated "803/804")', SPEC_GATE,
               level9_entrance_side_pairs, PAIR_SUMMARY),
    Checkpoint("pin table", "level-9 entrance north side not a wall", "1000/1000", SPEC_GATE,
               level9_entrance_north_open, count_true),
    Checkpoint("pin table", "pinned person rooms' north wall/wall pairs, levels 1-8",
               "5663/5663", SPEC_GATE,
               person_north_pairs, ratio_total),
    Checkpoint("SH-DOOR-01", "room palettes: outer 2; person, goriya inner 0; Zelda inner 2; "
               "other rooms' inner 0 / 2 / 3",
               "outer 2 in all; person inner 0 17000/17000; at the shape stage goriya 0 and "
               "Zelda 2 1000/1000, other inner = base | 2 (2 / 3 = 68.2 / 31.8%)",
               SPEC_SHAPES, room_palettes, PAIR_SUMMARY),
    Checkpoint("VA-REJ-02", "Zelda's room on layout $27",
               "1000/1000 at the shape stage (SH-ROOM-06); finished: not stated", SPEC_GATE,
               zelda_on_own_layout, count_true),
    Checkpoint("VA-REJ-02", "Ganon's room on layout $28",
               "1000/1000 at the shape stage (SH-ROOM-06); finished: not stated", SPEC_GATE,
               ganon_on_own_layout, count_true),
    Checkpoint("PS-BOSS-01", "levels 1-8 boss bank tier 0/1/2 (ROMs per level)",
               "L1 432/459/109 L2 467/430/103 L3 441/487/72 L4 465/467/68 L5 494/452/54 "
               "L6 478/470/52 L7 506/479/15 L8 487/501/12", SPEC_B2,
               boss_bank_tiers, TIER_SUMMARY),
    Checkpoint("PS-BOSS-06", "level 9's boss bank $A7", "1000/1000", SPEC_B2,
               lambda gw: gw.levels[8].boss_sprite_set == BossSpriteSet.C, count_true),
    Checkpoint("PS-MONLV-01", "enemy bank tier 0/1/2 (ROMs per level)",
               "per level 384-445 / 256-320 / 285-310 (expected 407/296/296)", SPEC_B2,
               enemy_bank_tiers, TIER_SUMMARY),
    Checkpoint("PS-MONLV-01", "ROMs by enemy tier counts (3,2,4) (3,3,3) (3,4,2) (4,2,3) "
               "(4,3,2) (5,2,2)", "110/199/105/250/235/101", SPEC_B2,
               enemy_tier_mix, distribution(TIER_MIXES)),
    Checkpoint("PS-MONRD-03", "Ganon's room item $8E and trigger $03", "1000/1000", SPEC_B2,
               ganon_room_item_and_trigger, count_true),
    Checkpoint("B2 checkpoint", "rooms on barred layouts: Lanmola, count-zero Lanmola, $35, "
               "traps, Gleeok, Ganon; flagged $3A/$3B",
               "0/6253 0/1750 0/4987 0/14240 0/2231 0/1000; 1063/4842", SPEC_B2,
               monster_bar_violations, PAIR_SUMMARY),
    Checkpoint("PS-BOSS-04", "rooms on barred layouts: Gohma, Gleeok push bit, four-headed "
               "Gleeok extra, Dodongo", "0/4279 0/2231 0/571 7/2880", SPEC_B2,
               boss_bar_violations, PAIR_SUMMARY),
    Checkpoint("PS-MONRD-02", "ROMs with Zelda on a barred layout", "0/1000", SPEC_B2,
               zelda_on_barred_layout, count_true),
    *(Checkpoint("B2 census", f"layout byte ${code:02X} cells per level, mean L1-L9",
                 CENSUS_SPEC[code], SPEC_B2, census_by_level(_layout_byte_is(code)),
                 PER_LEVEL_SUMMARY) for code in CENSUS_LAYOUT_BYTES),
    Checkpoint("B2 census", "person rooms per level, mean L1-L9", CENSUS_PERSONS_SPEC, SPEC_B2,
               census_by_level(lambda room: room.is_person), PER_LEVEL_SUMMARY),
    Checkpoint("B2 census", "rooms with the monster bit per level, mean L1-L9",
               CENSUS_FLAGGED_SPEC, SPEC_B2,
               census_by_level(lambda room: room.has_monster_bit), PER_LEVEL_SUMMARY),
    *(Checkpoint("B2.5 checkpoint", f"flag-set ${code:02X} rooms per level, mean L1-L9",
                 HINT_CENSUS_SPEC[code], SPEC_B25, census_by_level(_flagged_list(code)),
                 PER_LEVEL_SUMMARY) for code in HINT_CODES),
    Checkpoint("PS-HINT-06", "helpful levels 4 / 3 / 2", "803/182/15", SPEC_B25,
               helpful_level_count, distribution(HELPFUL_LEVEL_COUNTS)),
    Checkpoint("PS-HINT-02", "kept $0F rooms: exactly two in unhelpful levels / one in "
               "3,4,6,8 / both in one level", "1000 / 656 / 111", SPEC_B25,
               kept_bomb_upgrade_rooms, FLAG_COUNTS),
    Checkpoint("B2.5 checkpoint", "unhelpful levels' counted rooms 5 / 6", "709/291", SPEC_B25,
               unhelpful_room_count, distribution(UNHELPFUL_ROOM_COUNTS)),
    Checkpoint("B2.5 checkpoint", "ROMs whose two streams are counter prefixes", "1000/1000",
               SPEC_B25, hint_streams_hold, count_true),
    Checkpoint("PS-EGRP-03", "overworld enemies in dungeon monster rooms: blue/red Tektite, "
               "blue Moblin, red/blue Lynel, red Moblin",
               "3.71 / 2.48 / 2.02 / 2.00 / 1.97 / 1.95% of 143,465", SPEC_B4,
               overworld_enemy_shares, PAIR_SUMMARY),
    Checkpoint("PS-EGRP-03", "ROMs with an overworld enemy in a dungeon room", "963/1000",
               SPEC_B4, any_overworld_enemy_in_dungeon, count_true),
    Checkpoint("PS-EGRP-03", "Zol rooms with monster-byte bit 7, all four blocks", "0/10630",
               SPEC_B4, zol_rooms_with_bit_7, ratio_total),
    Checkpoint("PS-EGRP-04", "mixed lists with a Lanmola byte / more than 4 Zols",
               "0/30000 / 0/30000", SPEC_B4, mixed_list_checks, PAIR_SUMMARY),
    Checkpoint("PS-EGRP-05", "item-carrier operands set to $FF: $17 / $2A / $30",
               "0 / 254 / 215", SPEC_B4, item_carriers_off, FLAG_COUNTS),
    Checkpoint("PS-EGRP-06", "goriya tile $9E / $A2 / $A0 / $AC / $8E",
               "$9E 211 $A2 195 $A0 129 $AC 118 $8E 6", SPEC_B4, goriya_tile,
               per_thousand_by_code(GORIYA_TILES)),
    Checkpoint("PS-EGRP-06", "goriya tile $BC: tier-0 goriya level / other", "28/420 0/580",
               SPEC_B4, goriya_seed_slot, PAIR_SUMMARY),
    Checkpoint("PS-BGRP-02", "one-headed Gleeoks in boss rooms", "0/25000", SPEC_B4,
               one_headed_gleeoks, ratio_total),
    Checkpoint("PS-BGRP-03", "boss identities",
               "Aquamentus 3305; Manhandla 3056; Digdogger 2781 + 2756; Gohma 2149 + 2130; "
               "Patra 1880 + 1832; Dodongo 1457 + 1423; Gleeok 2/3/4 868/792/571", SPEC_B4,
               boss_identities, per_thousand_by_code(tuple(BOSS_IDENTITIES))),
    Checkpoint("PS-SPR-02/03", "fixed frame bytes: Wallmaster $AC/$9C / Gleeok $DA/$DC/$DE / "
               "open mouth = Aquamentus frame 4 - 2", "1000 / 1000 / 1000", SPEC_B5,
               fixed_frame_bytes, FLAG_COUNTS),
    Checkpoint("PS-SPR-02", "Aquamentus open-mouth operand $31 / $E4 / $E2", "$31 454 $E4 280 $E2 266",
               SPEC_B5, open_mouth, per_thousand_by_code(OPEN_MOUTH_VALUES)),
    Checkpoint("PS-SPR-03", "partner frame runs equal their primary's (goriya, darknut, "
               "wizzrobe, lynel, moblin, tektite)", "1000 each", SPEC_B5, partner_runs,
               FLAG_COUNTS),
    Checkpoint("PS-SPR-03", "partner frame runs differing from vanilla",
               "1000 / 1000 / 902 / 1000 / 903 / 1000", SPEC_B5, partner_runs_changed,
               FLAG_COUNTS),
    Checkpoint("B5 checkpoint", "boss rooms: boss in its level's block / common / elsewhere; "
               "level 9 common", "12712/25000 12288/25000 0/25000; 3929/5000", SPEC_B5,
               boss_placement, PAIR_SUMMARY),
    Checkpoint("B5 checkpoint", "Dodongo and Gleeok share a block / block 2 holds Digdogger / "
               "Patra", "0 / 179 / 259", SPEC_B5, boss_blocks, FLAG_COUNTS),
    Checkpoint("PS-COLOR-02", "nine color pairs distinct / all among the 23 PRG0 candidates",
               "1000 / 1000", SPEC_B5, color_sets_check, FLAG_COUNTS),
    Checkpoint("PS-COLOR-01", "level rooms' inner selector 2 / 3 / 0",
               "63.1 / 29.2 / 7.7%", SPEC_B5, inner_selector_shares, PAIR_SUMMARY),
    Checkpoint("B3 checkpoint", "ROMs with a progression item in a level-9 room", "0/1000",
               SPEC_B3, level9_room_progression, count_true),
    Checkpoint("B3 checkpoint", "ROMs with 1 or 2 progression items in level 9's cellars",
               "699/1000 (selected by the acceptance check, acceptance.md VA-REJ-08)", SPEC_B3,
               lambda gw: level9_cellar_progression(gw) in (1, 2), count_true),
    Checkpoint("B3 checkpoint", "ROMs whose level holds layout $28, L1-L9",
               "19 62 65 56 45 104 123 170 356", SPEC_B3, levels_with_layout(GANON_LAYOUT),
               ROMS_PER_LEVEL),
    Checkpoint("B3 checkpoint", "level-1 non-person rooms on layouts $0B/$0E/$0F/$12/$27",
               "$0B 6 $0E 10 $0F 23 $12 10 $27 21 (70 per 1,000)", SPEC_B3,
               level1_arriving_layouts, per_thousand_by_code(LEVEL1_ARRIVING_LAYOUTS)),
    Checkpoint("A45", "level-9 $4B room with at least one shutter side",
               "1000/1000", SPEC_GATE, level9_person_any_shutter, count_true),
    Checkpoint("VA-REJ-19", "level-9 $4B room north/east/west, S shutter W wall: "
               "SSS/SSW/WSS/SWS/WSW/WWS/SWW/other",
               "206/169/162/159/108/102/94/0", SPEC_GATE_19, level9_person_sides,
               distribution(LEVEL9_PERSON_SIDE_KEYS)),
    Checkpoint("VA-REJ-19", "level-9 $4B room trigger 0 by shutters 1/2/3 among "
               "north/east/west; trigger 1; other (trigger 0 total in 369-461)",
               "163/196/56/585/0", SPEC_GATE_19, level9_person_trigger,
               distribution(LEVEL9_PERSON_TRIGGER_KEYS)),
    Checkpoint("A48", "Zelda's same-level neighbours 1 / 2 / 3 / 4", "41/174/412/373",
               SPEC_GATE, zelda_neighbour_count, distribution(ZELDA_NEIGHBOUR_COUNTS)),
    Checkpoint("A48", "Zelda's neighbours with trigger byte $03", "1801/3117", SPEC_GATE,
               zelda_neighbours_trigger3, ratio_total),
    Checkpoint("VA-REJ-20", "items in level 9's non-Ganon trigger-3 rooms, per 1,000 ROMs",
               "key 394 bombs 176 five rupees 125 map 42 compass 0 other 0 (0.737 per ROM)", SPEC_GATE_20,
               last_boss_room_items, per_thousand_by_key(LAST_BOSS_ROOM_ITEM_KEYS)),
    Checkpoint("VA-REJ-20", "ROMs with the compass in a level-9 non-Ganon trigger-3 room", "0/1000",
               SPEC_GATE_20, last_boss_room_compass, count_true),
    Checkpoint("SH-MAP-05", "level 9's map on trigger 7 / 1 / 3 / other", "872/86/42/0", SPEC_SHAPES_U30,
               level9_map_trigger, distribution(MAP_TRIGGER_KEYS)),
    Checkpoint("SH-ROOM-13", "levels 1-8 item rooms (no triforce piece) on trigger 7", "53054/82760 (64.1%)",
               SPEC_SHAPES_U30, item_trigger7_levels_1_8, ratio_total),
    Checkpoint("SH-ROOM-13", "level 9 item rooms on trigger 1 or 7 (no Triforce of Power) on 7",
               "10134/15630 (64.8%)", SPEC_SHAPES_U30, item_trigger7_level9, ratio_total),
    Checkpoint("late gate", "finished-ROM door sides: mismatched pairs; side shares",
               "mismatched 16.79%; open 35.3 shutter 18.4 wall 15.1 bombable 16.0 locked 15.2;"
               " 298 pairs per ROM (500 seeds, as the spec reports)", SPEC_GATE,
               door_side_mix, DOOR_MIX_SUMMARY),
    Checkpoint("OW-ENTR-02", "door counts per dungeon 1-9 are 1,1,1,1,2,2,2,2,2", "1000/1000",
               SPEC_OW, door_counts_match, count_true),
    Checkpoint("OW-CAVE-01", "code 16 on one screen and code 20 on four", "1000/1000", SPEC_OW,
               sword_and_any_road_counts, count_true),
    Checkpoint("OW-CAVE-04", "take-any-road array = the code-20 screens in list order / ascending",
               "1000 / 652", SPEC_OW, any_road_array, FLAG_COUNTS),
    Checkpoint("OW-CAVE-04", "code-20 screens: F bits 5-4 = V (non-bracelet); PRG0 F kept (bracelet)",
               "3777/3777 223/223", SPEC_OW, any_road_position_index, PAIR_SUMMARY),
    Checkpoint("OW-CAVE-02", "screens outside OW-APP-A1 (and not 36) keep their PRG0 cave byte",
               "1000/1000", SPEC_OW, unenrolled_screens_kept, count_true),
    Checkpoint("OW-CAVE-02", "screens whose destination differs from PRG0, per ROM",
               "59-72, median 68", SPEC_OW, destinations_changed, mean_of("{:.2f}")),
    Checkpoint("OW-CAVE-02", "entries ending with their PRG0 code, per ROM", "4.3", SPEC_OW,
               entries_keeping_code, mean_of("{:.2f}")),
    Checkpoint("OW-CAVE-03", "dungeons with no door on S(d)", "9000/9000", SPEC_OW,
               start_room_ban, ratio_total),
    Checkpoint("OW-CAVE-03", "dungeons 1-4 on their PRG0 door", "9 / 16 / 20 / 9", SPEC_OW,
               dungeons_on_prg0_door, FLAG_COUNTS),
    Checkpoint("OW-CAVE-03", "code 16 on an OW-APP-A3 screen / on 119", "1000 / 45", SPEC_OW,
               wood_sword_screen, FLAG_COUNTS),
    Checkpoint("OW-CAVE-05", "armos screen A = 36/28/52/61/78", "201/192/208/201/198", SPEC_OW,
               armos_first_screen, distribution(ARMOS_FIRST_SCREENS)),
    Checkpoint("OW-CAVE-05", "formation a permutation with listed Xs / LevelBlockAttrsA[36] = $43",
               "1000 / 1000", SPEC_OW, armos_tables, FLAG_COUNTS),
    Checkpoint("OW-CAVE-05", "F bytes with both high bits: one, at A / none", "799 / 201", SPEC_OW,
               neither_quest_bytes, FLAG_COUNTS),
    Checkpoint("OW-CAVE-05", "vacated screen keeps its PRG0 cave byte", "799/799", SPEC_OW,
               vacated_screen_kept, ratio_total),
    Checkpoint("OW-CAVE-05", "screens per code: 0 holds 35 / 36; 21 holds 2; 32 holds 2; 33 holds 9; "
               "35 holds 7", "799 / 201 / 192 / 208 / 201 / 198", SPEC_OW, code_screen_counts, FLAG_COUNTS),
    Checkpoint("OW-CAVE-05", "LevelBlockAttrsF[36] = $03 / $23", "955 / 45", SPEC_OW, screen36_f,
               FLAG_COUNTS),
    Checkpoint("OW-WARP-01", "recorder bytes follow each dungeon 1-8's entry door", "1000/1000",
               SPEC_OW, recorder_follows_doors, count_true),
    Checkpoint("OW-WARP-01", "distinct recorder screens, per ROM", "7.99", SPEC_OW,
               recorder_distinct_screens, mean_of("{:.3f}")),
    Checkpoint("OW-SHOP-02", "shop items: PRG0 multiset / distinct per shop", "1000 / 1000", SPEC_OW,
               shop_stock, FLAG_COUNTS),
    Checkpoint("OW-SHOP-03", "shop prices within 20 of a PRG0 price, 1-254; ring at 250; heart at 10",
               "all; 416/1000; 279/1000", SPEC_OW, shop_prices, PAIR_SUMMARY),
    Checkpoint("OW-SHOP-04", "six extra price bytes in range", "1000/1000", SPEC_OW,
               extra_prices_in_range, count_true),
    Checkpoint("OW-SHOP-04", "six extra price bytes, mean (uniform: 40 68 32.5 100 10.5 20)",
               "uniform over each range", SPEC_OW, extra_prices, EXTRA_PRICE_SUMMARY),
    Checkpoint("OW-SHOP-05", "blue candle in the wooden-sword cave ware 0 and cave 17 ware 1",
               "1000/1000", SPEC_OW, extra_candles, count_true),
    Checkpoint("OW-SHOP-06", "front-door guarantees / codes 29-31 on 4 screens each / code 32 on 2",
               "1000 / 1000 / 208", SPEC_OW, shop_front_doors, FLAG_COUNTS),
    Checkpoint("OW-START-01", "S in the list / S = 119 / S carries a cave / "
               "a dungeon door / code 16 / S's PRG0 byte $21 or $2F",
               "1000 / 18 / 977 / 126 / 9 / 0 (last: PS-OWM-03)", SPEC_OW,
               start_screen_rules, FLAG_COUNTS),
    Checkpoint("OW-START-01", "Link's start Y from S: $8D/$7D/$5D/$AD", "843/80/41/36", SPEC_OW,
               start_y_value, distribution(START_Y_VALUES)),
    Checkpoint("OW-START-01", "start screens: least-most per screen; chi-square vs uniform",
               "12-31 each; 119 in 18; chi-square 47.9 on 50 df", SPEC_OW, start_screen,
               START_SCREEN_SPREAD),
    Checkpoint("PS-OWM-01/03", "non-candidate screens keep PRG0's monster pair (119 and S aside)",
               "1000/1000", SPEC_B8, owm_non_candidates_kept, count_true),
    Checkpoint("PS-OWM-01/03", "screen 11 keeps $10 / screen 119's byte differs / its flag differs",
               "18 / 926 / 287", SPEC_B8, owm_screens, FLAG_COUNTS),
    Checkpoint("PS-OWM-03", "S holds byte $00 with bit 7 clear, S not 119", "982/982", SPEC_B8,
               start_screen_takes_119s_pair, ratio_total),
    Checkpoint("PS-OWM-03", "119's other seven D bits keep PRG0's value", "1000/1000", SPEC_B8,
               screen_119_layout_kept, count_true),
    Checkpoint("PS-OWM-02", "no barred monster pair on its barred screens", "1000/1000", SPEC_B8,
               owm_no_barred_placement, count_true),
    Checkpoint("PS-HP-01", "enemy nibbles and rope within 2 / mean move / share unchanged",
               "1000/1000", SPEC_B8, enemy_hp_walk, HP_WALK_SUMMARY),
    Checkpoint("PS-HP-02", "boss nibbles within 2 / mirrored operands / Gleeok head 4-8",
               "1000 / 1000 / 1000", SPEC_B8, boss_hp_walk, FLAG_COUNTS),
    Checkpoint("PS-HP-02", "Gleeok head operand 4/5/6/7/8", "about 200 each", SPEC_B8,
               gleeok_head_hp, distribution(GLEEOK_HEAD_VALUES)),
    Checkpoint("PS-L9REC-01", "level-9 records name the $37/$3E rooms / L9 boss record off vanilla / "
               "L1-8 boss records vanilla", "1000 / 988 / 1000", SPEC_B8, level9_records_match,
               FLAG_COUNTS),
    Checkpoint("PS-EGRP-05", "red-Wizzrobe overworld byte runs written", "240/1000", SPEC_B4,
               wizzrobe_overworld_patch, count_true),
    Checkpoint("VA-REJ-08", "none of the five long items in a level-9 room or item cellar",
               "1000/1000 (post-shapes-b3.md R6)", SPEC_B6, long_items_outside_level9, count_true),
)


CHECKPOINTS = (
    *CHECKPOINTS,
    Checkpoint("HT-SEL-02", "white-sword text selector is $66", "1000/1000", SPEC_HINT,
               lambda gw: gw.white_sword_text_selector == 0x66, count_true),
    Checkpoint("HT-SEL-02", "hint-shop offer selectors in order $18/$4E/$50/$52/$54/$56",
               "1000/1000", SPEC_HINT,
               lambda gw: hint_shop_offer_selectors(gw) == EXPECTED_OFFER_SELECTORS, count_true),
    Checkpoint("HT-SEL-02", "six hint-shop offer prices are 10..60", "1000/1000", SPEC_HINT,
               lambda gw: all(10 <= p <= 60 for p in hint_shop_prices(gw)), count_true),
    Checkpoint("HT-SEL-01", "first 8 bytes of selector tables A/B: no $26, valid values",
               "1000/1000", SPEC_HINT, underworld_selector_tables, FLAG_COUNTS),
    Checkpoint("HT-TEXT-02", "slot 0 shows a greeting / a pool quote, per 1,000 ROMs (wording-free); "
               "DIFFERS BY OWNER RULING: ZORA's slot 0 shows only its own quotes",
               "greeting 1000 (exclamation 509, period 491)", SPEC_HINT,
               _hint_record("slot_texts"), _text_kind_summary((0,), (GREETING, POOL_TEXT))),
    Checkpoint("HT-TEXT-02", "slots 1-44 (less 27, 34) showing a pool / composed text, or falling back to "
               "the greeting / a blank, summed per 1,000 ROMs (wording-free); slot 9 DIFFERS BY OWNER "
               "RULING (three more quotes of its own)",
               "no figure (fallback only where a slot has no candidates)", SPEC_HINT,
               _hint_record("slot_texts"),
               _text_kind_summary(SHOWN_SLOTS[1:], (POOL_TEXT, COMPOSED, GREETING, BLANK))),
    Checkpoint("HT-TEXT-02", "slot 19 shows a white-sword item hint, when the ware is one of the four "
               "cases / otherwise (wording-free: a slot-19 text that recurs with one case and only with it)",
               "12/221 when matching, 0/779 otherwise", SPEC_HINT,
               _hint_record("white_sword_hint_shown"), _white_sword_hint_summary()),
    Checkpoint("HT-HINT-01", "requirement forms shown per 1,000 ROMs (wording-free: texts whose "
               "every occurrence matches one HT-HINT-01 candidate rebuilt from the ROM)",
               "boss 3385 ladder 758 bracelet 190 no bracelet 180 raft 91 no raft 227 recorder 110 "
               "bow 52", SPEC_HINT, _hint_record("requirement_shown"), REQUIREMENT_SUMMARY),
    Checkpoint("HT-HINT-01", "rule 2 on the ROM's item records: tested / blocked with the sword "
               "alone / ladder / recorder / bow candidates, per 1,000 ROMs",
               "tested 12107 blocked 2094 ladder 1546 recorder 292 bow 189", SPEC_HINT,
               _hint_record("inside_dungeon_outcomes"), _inside_dungeon_summary()),
    Checkpoint("HT-HINT-01/02", "entry 10's name form when shown (wording-free); entries 12 / 10 / 11 "
               "shown (slots 3 / 6 / 7)",
               "SAME 127 HUMAN 82 OLD MAN 48 OLD WOMAN 66 MERCHANT 69 MOBLIN 98; shown 514 / 490 / 473",
               SPEC_HINT, _hint_record("name_shown"), NAME_SUMMARY),
    Checkpoint("HT-HINT-01/02", "level-9 trio shown by slot (wording-free)",
               "35 silver 511; 36 ganon 351, zelda 166; 37 zelda 166, compass 337", SPEC_HINT,
               _hint_record("trio_shown"), TRIO_SUMMARY),
    Checkpoint("HT-APP-A1", "level-location entry shown, naming its door-screen region "
               "(wording-free), levels 1-9",
               "3974 for levels 1-8 (about 497 each); 475 for level 9", SPEC_HINT,
               _hint_record("location_shown"), LOCATION_SUMMARY),
)


def measure_rom(gw: GameWorld) -> list[Any]:
    """Every checkpoint's per-ROM value, in registry order."""
    return [cp.per_rom(gw) for cp in CHECKPOINTS]


CHECKPOINTS = (
    *CHECKPOINTS,
    Checkpoint("VA-REJ-17", "recorder / bracelet / raft / bow in a recorder-list level room",
               "0/1866 10/844 8/1848 6/1853 (all four blocks)", SPEC_E1,
               items_in_list_rooms(RECORDER_LIST_ITEMS, RECORDER_LIST), RATIOS),
    Checkpoint("VA-REJ-17", "bow / silver arrow / recorder / raft in a bow-list level room",
               "0/1853 12/1873 9/1866 9/1848 (all four blocks)", SPEC_E1,
               items_in_list_rooms(BOW_LIST_ITEMS, BOW_LIST), RATIOS),
    Checkpoint("VA-REJ-17", "wand / bow / raft in a sword-list level room",
               "29/857 (wand; others 26-47 in about 1,850)", SPEC_E1,
               items_in_list_rooms(SWORD_LIST_ITEMS, SWORD_LIST), RATIOS),
    *(Checkpoint("VA-REJ-07", f"{item.name.lower()} in level 1/2/.../9 / cave slot",
                 "not stated", SPEC_E1, long_item_level(item), distribution(PLACE_KEYS))
      for item in LONG_ITEMS),
    Checkpoint("VA-REJ-08", "long items per ROM in levels 1-6 / levels 7-8 / cave slots",
               "not stated", SPEC_E1, long_item_split, SPLIT_SUMMARY),
    Checkpoint("VA-REJ-07", "tracked item types in level 9 per ROM, mean", "not stated", SPEC_E1,
               tracked_in_level9, mean_of()),
    Checkpoint("VA-REJ-07", "self-locks: entrance need / coast ladder / white-sword own need / "
               "ladder in a ladder room", "0 / 0 / 0 / 0 (implied)", SPEC_E1, self_locks, FLAG_COUNTS),
)


CHECKPOINTS = (
    *CHECKPOINTS,
    Checkpoint("VA-REJ-07", "E1's closure, replayed on the finished ROM, accepts it",
               "1000/1000 (every corpus final passed E1)", SPEC_E1, e1_replay, count_true),
)


CHECKPOINTS = (
    *CHECKPOINTS,
    Checkpoint("FP-START-01", "starting Items vector: new file / second-quest switch; "
               "Continue hearts $02", "1000 / 1000 (the vector); 1000", SPEC_B10,
               b10_start_state, FLAG_COUNTS),
    Checkpoint("FP-LOCK-02", "credits: line 15's record PRG0's / lines 12-14's entries constant",
               "1000 / 1000", SPEC_B10_F10, b10_credits_locked, B10_CREDITS_SUMMARY),
    Checkpoint("FP-MMG-01", "money-game amounts p1/p2/p3/s/l",
               "p1 1..20, p2 30..50, p3 1..20, s 10..30, l 25..75", SPEC_B10,
               b10_mmg_amounts, B10_MMG_SUMMARY),
    Checkpoint("FP-SWORD-01", "white/magical sword heart requirements",
               "white 4..6, magical 10..14", SPEC_B10, b10_sword_hearts, B10_SWORD_SUMMARY),
    Checkpoint("FP-BOMB-01", "bomb-upgrade price and capacity",
               "price 75..125, capacity 2..6", SPEC_B10, b10_bomb_upgrade, B10_BOMB_SUMMARY),
    Checkpoint("FP-TRIF-01", "level-9 refusal text states the count eight (8 or EIGHT)",
               "1000/1000", SPEC_B10, b10_level9_refusal, count_true),
    Checkpoint("FP-RESET-01..FP-LEVEL-01", "B10 constant DATA items",
               "all correct in 1000/1000", SPEC_B10, b10_constants, FLAG_COUNTS),
    Checkpoint("FP-TITLE-01", "title-screen seed number and version line (re-authored)",
               "seed matches, version constant", SPEC_B10, b10_title, B10_TITLE_SUMMARY),
)

CHECKPOINTS = (
    *CHECKPOINTS,
    Checkpoint("FP-PERSON-01", "cave person appearances $58/$59/$5A/$5B over 17 types per ROM",
               "4321/4225/4246/4208", SPEC_B10, person_appearances, SUMMED_COUNTS),
    Checkpoint("FP-ENTR-01", "arrival code 2 in dungeons 1-9", "1000/1000", SPEC_B10,
               dungeon_arrival_codes, count_true),
    Checkpoint("FP-ENTR-02", "exit-room count 0 in dungeon 1-9 / bit 7 set in all nine",
               "830/832/819/798/747/159/578/561/171 / 1000", SPEC_B10, exit_room_count_zero,
               FLAG_COUNTS),
)
